spring:
  data:
    rest:
      default-page-size: 50

  mvc:
    favicon:
      enabled: false
      
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
  jta:
    enable: false
  profiles:
    active: CZBK


server:
  servlet-path: /*
  context-path: /embargos

commerzbank:
  embargos:
    files:
      monitoring-interval-in-seconds: 5
      stable-size-time-in-millis: 5000
      suffix-file-filter-pet: pet
      suffix-file-filter-inf: inf
      suffix-file-filter-emb: emb
      suffix-file-filter-tra: tra
      suffix-file-filter-lev: lev
      suffix-file-filter-err: err
      suffix-file-filter-fin: fin
      suffix-file-filter-con: con
    beanio:
      config-path:
        cuaderno63: beanio/cuaderno63.xml
        aeat: beanio/aeat.xml
  comunes:
    beanio:
      config-path:
        contabilidad: beanio/contabilidad_salida.xml  
        mt942: beanio/mt942.xml

