spring:
  data:
    rest:
      default-page-size: 50
  datasource:
    initialize: false
    continue-on-error: false
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: COMM_EMBARGOS_DES
    password: PASSWORD
    sql-script-encoding: UTF-8
  mvc:
    favicon:
      enabled: false 
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
  jta:
    enable: false

server:
  servlet-path: /*
  context-path: /embargos
  port: 8090


commerzbank:
  embargos:
    files:
      path:
        monitoring: /Seizure_Files/incoming/
        processed: /Seizure_Files/processed/
        generated: /Seizure_Files/generated/
        error: /Seizure_Files/error/
      monitoring-interval-in-seconds: 5
      suffix-file-filter-pet: pet
      suffix-file-filter-inf: inf
      suffix-file-filter-emb: emb
      suffix-file-filter-tra: tra
      suffix-file-filter-lev: lev
      suffix-file-filter-err: err
      suffix-file-filter-fin: fin
      suffix-file-filter-con: con
    beanio:
      config-path:
        cuaderno63: beanio/cuaderno63.xml
        aeat: beanio/aeat.xml
        
ds-comun:
   url: jdbc:oracle:thin:@localhost:xe
   username: COMM_COMUNES_DES
   password: PASSWORD
   driver-class-name: oracle.jdbc.driver.OracleDriver

        