spring:
  data:
    rest:
      default-page-size: 50
  datasource:
    initialize: false
    continue-on-error: false
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.21.0.123:1521:DBADQUIRA
    username: COMM_EMBARGOS_DES
    password: comm_3mb4
    sql-script-encoding: UTF-8
  mvc:
    favicon:
      enabled: false
      
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
  jta:
    enable: false
  profiles:
    active: DES
  ds-comun:
    url: jdbc:oracle:thin:@172.21.0.123:1521:DBADQUIRA
    username: COMM_COMUNES_DES
    password: comm_c0mu
    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  servlet-path: /*
  context-path: /embargos

commerzbank:
  embargos:
    files:
      path:
        monitoring: /Seizure_Files/incoming/
        processed: /Seizure_Files/processed/
        generated: /Seizure_Files/generated/
        error: /Seizure_Files/error/
      monitoring-interval-in-seconds: 5
      suffix-file-filter-pet: pet
      suffix-file-filter-inf: inf
      suffix-file-filter-emb: emb
      suffix-file-filter-tra: tra
      suffix-file-filter-lev: lev
      suffix-file-filter-err: err
      suffix-file-filter-fin: fin
      suffix-file-filter-con: con
    beanio:
      config-path:
        cuaderno63: beanio/cuaderno63.xml
        aeat: beanio/aeat.xml
  jasper:
    temp: C:/temp/
  comunes:
    beanio:
      config-path:
        contabilidad: beanio/contabilidad_salida.xml
        mt942: beanio/mt942.xml

