--- SCRIPT DEL DDL INICIAL PARA LA CREACION DE LA BBDD DE EMBARGOS: ---

CREATE TABLE "ACCNT_RDB" (
  "DAY_ID" VARCHAR2(1) NOT NULL
 ,"BUS_DATE" DATE
 ,"CH_FLAG" VARCHAR2(1)
 ,"EOD_ENTRY_DATE" DATE
 ,"BRANCH" VARCHAR2(1) NOT NULL
 ,"BRANCH_NO" VARCHAR2(3)
 ,"SOURCE" VARCHAR2(8) NOT NULL
 ,"MAST_ACCT_NO" VARCHAR2(15) NOT NULL
 ,"MAST_GL_NO" VARCHAR2(14)
 ,"MAST_CUST_NO" VARCHAR2(13)
 ,"MAST_LZB_FLAG" VARCHAR2(1)
 ,"MAST_INSTR_TYPE" VARCHAR2(6)
 ,"MAST_BAL_KEY" VARCHAR2(3)
 ,"MAST_CREDIT_TYPE" VARCHAR2(3)
 ,"MAST_COLL_KEY" VARCHAR2(5)
 ,"MAST_CURR" VARCHAR2(3)
 ,"MAST_OPEN_BOOK_BAL" NUMBER(15,2)
 ,"MAST_CORP_DDA" VARCHAR2(15)
 ,"MAST_POOL_LEVEL" VARCHAR2(1)
 ,"MAST_POOL_TYPE" VARCHAR2(1)
 ,"MAST_PARENT_DDA" VARCHAR2(15)
 ,"MAST_ACCT_TITLE" VARCHAR2(35)
 ,"MAST_STAT_CYC" VARCHAR2(3)
 ,"MAST_ACCT_STAT" VARCHAR2(2)
 ,"MAST_MAIL_IND" VARCHAR2(1)
 ,"MAST_PART_HOLD_IND" VARCHAR2(1)
 ,"MAST_CHRG_CNT" NUMBER
 ,"MAST_SECR_CODE" VARCHAR2(6)
 ,"MAST_CON_BAL" NUMBER(15,2)
 ,"MAST_OVDR_LIM" NUMBER(15,2)
 ,"MAST_IOL" NUMBER(15,2)
 ,"MAST_LST_STMT_DATE" VARCHAR2(10)
 ,"MAST_LST_STMT_DATE_PD" VARCHAR2(10)
 ,"MAST_INT_REV_DATE" VARCHAR2(10)
 ,"MAST_NXT_STMT_DATE" VARCHAR2(10)
 ,"MAST_CRLM_REV_DATE" VARCHAR2(10)
 ,"MAST_ACCT_POST_DATE" VARCHAR2(10)
 ,"MAST_NO_FINC_ACT_DATE" VARCHAR2(10)
 ,"MAST_LST_STAT_CHG_DATE" VARCHAR2(10)
 ,"MAST_SET_UP_DATE" VARCHAR2(10)
 ,"MAST_LAST_GL_DATE" VARCHAR2(10)
 ,"MAST_STATI_ACC_TRAN_DATE" VARCHAR2(10)
 ,"MAST_INT_CHG_ACCT" VARCHAR2(15)
 ,"MAST_FEE_CHG_ACCT" VARCHAR2(15)
 ,"MAST_MIN_CHG" NUMBER(15,2)
 ,"MAST_MAX_CHG" NUMBER(15,2)
 ,"MAST_LOCAL_POST" NUMBER(15,2)
 ,"MAST_FGN_POST" NUMBER(15,2)
 ,"MAST_TRAN_CHG" NUMBER(15,2)
 ,"MAST_STMT_DB" NUMBER(15,2)
 ,"MAST_STMT_DB_PD" NUMBER(15,2)
 ,"MAST_STMT_CR" NUMBER(15,2)
 ,"MAST_STMT_CR_PD" NUMBER(15,2)
 ,"MAST_TRAN_AMT" NUMBER(15,2)
 ,"MAST_TRAN_AMT_PD" NUMBER(15,2)
 ,"MAST_TURN_CHG" NUMBER(15,2)
 ,"MAST_TOT_STMT_CNT" NUMBER
 ,"MAST_INT_STMT_FREQ" NUMBER
 ,"MAST_TURN_CHG_IND" VARCHAR2(1)
 ,"MAST_MIN_MAX_IND" VARCHAR2(1)
 ,"MAST_TOT_TRAN" NUMBER
 ,"MAST_TOT_TRAN_PD" NUMBER
 ,"MAST_TRAN_TAB_IND" VARCHAR2(1)
 ,"MAST_STMT_NEEDED" VARCHAR2(1)
 ,"MAST_TRAN_CHG_EACH" NUMBER(15,2)
 ,"MAST_TRAN_FREE" NUMBER
 ,"MAST_PREV_BK_BAL" NUMBER(15,2)
 ,"MAST_PREV_AVAIL_BAL" NUMBER(15,2)
 ,"MAST_PREV_END_BK_BAL" NUMBER(15,2)
 ,"MAST_AVAIL_BAL_LST_STMT" NUMBER(15,2)
 ,"MAST_BK_BAL_LST_STMT" NUMBER(15,2)
 ,"MAST_AVAIL_BAL_LST_INT_STMT" NUMBER(15,2)
 ,"MAST_BK_BAL_LST_INT_STMT" NUMBER(15,2)
 ,"MAST_CR_DATE_AMT" NUMBER(15,2)
 ,"MAST_DB_DATE_AMT" NUMBER(15,2)
 ,"MAST_TRAN_DATE_CNT" NUMBER
 ,"MAST_STATI_CR_TRANS" NUMBER
 ,"MAST_STATI_DB_TRANS" NUMBER
 ,"MAST_TOT_DB_AMT" NUMBER(15,2)
 ,"MAST_TOT_CR_AMT" NUMBER(15,2)
 ,"MAST_ACCR_BASIS" VARCHAR2(1)
 ,"MAST_REC_IN_USE_FLAG" VARCHAR2(1)
 ,"MAST_BR_CODE" VARCHAR2(2)
 ,"MAST_LAST_STMT_NO" NUMBER
 ,"MAST_LAST_STMT_NO_PD" NUMBER
 ,"MAST_CURRENT_MIN_BAL" NUMBER(15,2)
 ,"MAST_CURRENT_MAX_BAL" NUMBER(15,2)
 ,"MAST_AGE_DATE" VARCHAR2(10)
 ,"MAST_CABLE_DAYS" NUMBER
 ,"MAST_ACCT_TYPE" VARCHAR2(3)
 ,"MAST_ADVICE_IND" VARCHAR2(1)
 ,"MAST_AVG_BAL_CHG" NUMBER(15,2)
 ,"MAST_AVG_BAL_TOT_FEE" NUMBER(15,2)
 ,"MAST_AVG_BAL_TBL" NUMBER
 ,"MAST_INSUFF_FUND_IND" VARCHAR2(1)
 ,"MAST_NOTICE_DAYS" NUMBER
 ,"MAST_CORRESP_CALL_ACCT" VARCHAR2(15)
 ,"MAST_STOP_PAYMENT" NUMBER
 ,"MAST_EXTERNAL_ACCT_NO" VARCHAR2(35)
 ,"MAST_ACCT_TERM_DATE" VARCHAR2(10)
 ,"MAST_CASHFLOW_IND" VARCHAR2(1)
 ,"MAST_OD_COUNTER" NUMBER
 ,"MAST_POST_CR_INT_FLAG" VARCHAR2(1)
 ,"MAST_AUTH_KEY" VARCHAR2(1)
 ,"MAST_CASH_MGNT_IND" VARCHAR2(1)
 ,"MAST_SPECIAL_IND" VARCHAR2(1)
 ,"MAST_FCDAIL_REV_FLAG" VARCHAR2(1)
 ,"MAST_FCDAIL_KEY" VARCHAR2(21)
 ,"MAST_ACCT_CLOSE_DATE" VARCHAR2(10)
 ,"MAST_CMI_STMT_NO" NUMBER
 ,"MAST_EXT_ACCNT_NO" VARCHAR2(23)
 ,"MAST_ORIG_SET_UP_DATE" VARCHAR2(10)
 ,"MAST_CASH_MGMT_CHG" NUMBER(15,2)
 ,"MAST_CASH_MGMT_TOT_FEE" NUMBER(15,2)
 ,"MAST_CASH_MGMT_TBL" NUMBER
 ,"MAST_MOF_NO" VARCHAR2(10)
 ,"MAST_T4M_CUSTOMER" VARCHAR2(1)
 ,"MAST_TURNOVER_TYPE" VARCHAR2(1)
 ,"MAST_COMM_ON_DEBIT_CHG" NUMBER(15,2)
 ,"MAST_COMM_ADJ" NUMBER(15,2)
 ,"MAST_TAX_CHG_IND" VARCHAR2(1)
 ,"MAST_TAX_CHG" NUMBER(15,2)
 ,"MAST_TODAY_BACKVALUE_AMOUNT" NUMBER(15,2)
 ,"MAST_CASH_MGT_INC_ACCRUAL" NUMBER(15,2)
 ,"MAST_TRAN_TURN_INC_ACCRUAL" NUMBER(15,2)
 ,"MAST_POST_INC_ACCRUAL" NUMBER(15,2)
 ,"MAST_MINMAX_CHG_TOTAL" NUMBER(15,2)
 ,"MAST_GMC_AMOUNT" NUMBER(15,2)
 ,"MAST_NEXT_DAY_CR" NUMBER(15,2)
 ,"MAST_NEXT_DAY_DR" NUMBER(15,2)
 ,"MAST_COMM_ON_DEBIT_ACCRUAL" NUMBER(15,2)
 ,"MAST_NEED_EOD_MOFHIST" VARCHAR2(1)
 ,"MAST_LAST_INT_STMT_DATE" VARCHAR2(10)
 ,"MAST_LAST_INT_STMT_DATE2" VARCHAR2(10)
 ,"MAST_ACCT_DORM_POST_DATE" VARCHAR2(10)
 ,"MAST_DD_NS_IND" VARCHAR2(1)
 ,"MAST_REOPEN_ALLOWED" VARCHAR2(1)
 ,"MAST_OPER_ID" VARCHAR2(3)
 ,"MAST_INT_STMT_BEG_DATE1" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE2" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE3" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE4" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE5" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE6" VARCHAR2(10)
 ,"MAST_INT_STMT_BEG_DATE7" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE1" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE2" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE3" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE4" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE5" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE6" VARCHAR2(10)
 ,"MAST_INT_STMT_END_DATE7" VARCHAR2(10)
 ,"MAST_CR_INT_AMT1" NUMBER(15,2)
 ,"MAST_CR_INT_AMT2" NUMBER(15,2)
 ,"MAST_CR_INT_AMT3" NUMBER(15,2)
 ,"MAST_CR_INT_AMT4" NUMBER(15,2)
 ,"MAST_CR_INT_AMT5" NUMBER(15,2)
 ,"MAST_CR_INT_AMT6" NUMBER(15,2)
 ,"MAST_CR_INT_AMT7" NUMBER(15,2)
 ,"MAST_DR_INT_AMT1" NUMBER(15,2)
 ,"MAST_DR_INT_AMT2" NUMBER(15,2)
 ,"MAST_DR_INT_AMT3" NUMBER(15,2)
 ,"MAST_DR_INT_AMT4" NUMBER(15,2)
 ,"MAST_DR_INT_AMT5" NUMBER(15,2)
 ,"MAST_DR_INT_AMT6" NUMBER(15,2)
 ,"MAST_DR_INT_AMT7" NUMBER(15,2)
 ,"MAST_CR_ACCR_TO_DATE" NUMBER(15,2)
 ,"MAST_CR_ACCR_TO_DATE_PD" NUMBER(15,2)
 ,"MAST_DR_ACCR_TO_DATE" NUMBER(15,2)
 ,"MAST_DR_ACCR_TO_DATE_PD" NUMBER(15,2)
 ,"MAST_BACK_VAL_DATE" VARCHAR2(10)
 ,"MAST_CR_INT_ADJ" NUMBER(15,2)
 ,"MAST_DR_INT_ADJ" NUMBER(15,2)
 ,"MAST_CR_INT_THIS_YR" NUMBER(15,2)
 ,"MAST_DB_INT_THIS_YR" NUMBER(15,2)
 ,"MAST_CR_AVG_INT_RATE" NUMBER(15,2)
 ,"MAST_ACCR_BACK_VAL_DATE" VARCHAR2(10)
 ,"MAST_AVG_MO_BAL" NUMBER(15,2)
 ,"MAST_NOW_CR_INT_POSTED1" NUMBER
 ,"MAST_NOW_CR_INT_POSTED2" NUMBER
 ,"MAST_NOW_CR_INT_POSTED3" NUMBER
 ,"MAST_NOW_CR_INT_POSTED4" NUMBER
 ,"MAST_NOW_CR_INT_POSTED5" NUMBER
 ,"MAST_NOW_CR_INT_POSTED6" NUMBER
 ,"MAST_NOW_CR_INT_POSTED7" NUMBER
 ,"MAST_NOW_TOTAL_CR_INT" NUMBER(15,2)
 ,"MAST_NOW_PREV_START_DATE" VARCHAR2(10)
 ,"MAST_NOW_CUR_START_DATE" VARCHAR2(10)
 ,"MAST_NOW_POSTED_CR_INT" NUMBER(15,2)
 ,"MAST_MOF_AVAIL_BAL" NUMBER(15,2)
 ,"MAST_VALID_TRANS" NUMBER
 ,"MAST_POST_FCDAIL_REV_FLAG" VARCHAR2(1)
 ,"MAST_POST_FCDAIL_KEY" VARCHAR2(21)
 ,"MAST_TODAY_DB_AMT" NUMBER(15,2)
 ,"MAST_TODAY_CR_AMT" NUMBER(15,2)
 ,"MAST_COINFO_INDICATOR" VARCHAR2(1)
 ,"MAST_COINFO_SYSTEM_IND" VARCHAR2(1)
 ,"MAST_COINFO_TIME_INTERVAL" NUMBER
 ,"MAST_COINFO_TIME_REFERENCE" VARCHAR2(1)
 ,"MAST_COINFO_FIRST_STATEMENT" NUMBER
 ,"MAST_COINFO_LAST_STMT_NO" NUMBER
 ,"MAST_COINFO_LAST_MSG_TIME" NUMBER
 ,"MAST_COINFO_LAST_MSG_DATE" DATE
 ,"MAST_COINFO_LAST_MSG_BAL" NUMBER(15,2)
 ,"MAST_LIQMGT_INDICATOR" VARCHAR2(1)
 ,"MAST_LIQMGT_TIME_INTERVAL" NUMBER
 ,"MAST_LIQMGT_TIME_REFERENCE" VARCHAR2(1)
 ,"MAST_LIQMGT_FIRST_STATEMENT" NUMBER
 ,"MAST_LIQMGT_LAST_STMT_NO" NUMBER
 ,"MAST_LIQMGT_LAST_MSG_TIME" NUMBER
 ,"MAST_LIQMGT_LAST_MSG_DATE" DATE
 ,"MAST_IBAN_ELECT" VARCHAR2(27)
 ,"MAST_IBAN_PAPER" VARCHAR2(38)
 ,"MAST_SWIFT_FEES" NUMBER(15,2)
 ,"MAST_SWIFT_FEES_ACCRUAL" NUMBER(15,2)
 ,"MAST_MMACB0" NUMBER(15,2)
 ,"MAST_MMACB_FEE0" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL0" NUMBER(15,2)
 ,"MAST_MMACB5" NUMBER(15,2)
 ,"MAST_MMACB6" NUMBER(15,2)
 ,"MAST_MMACB_FEE1" NUMBER(15,2)
 ,"MAST_MMACB_FEE2" NUMBER(15,2)
 ,"MAST_MMACB_FEE3" NUMBER(15,2)
 ,"MAST_MMACB_FEE4" NUMBER(15,2)
 ,"MAST_MMACB_FEE5" NUMBER(15,2)
 ,"MAST_MMACB_FEE6" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL1" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL2" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL3" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL4" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL5" NUMBER(15,2)
 ,"MAST_MMACB_ACCRUAL6" NUMBER(15,2)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "ACCNT_RDB_IX" on "ACCNT_RDB" (
  "DAY_ID"
 ,"MAST_ACCT_STAT"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 524288
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "APUNTE_CONTABLE" (
  "SECUENCIA_APUNTE" NUMBER NOT NULL
 ,"COD_APUNTE_CONTABLE" NUMBER NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"COD_TRABA" NUMBER
 ,"IMPORTE" NUMBER
 ,"CUENTA_DEBE" VARCHAR2(20)
 ,"CUENTA_HABER" VARCHAR2(20)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"NUMERO_ORDEN_CUENTA" NUMBER
 ,"FECHA_VALOR" NUMBER(14,0)
 ,"TIME_STAMP" NUMBER(14,0)
 ,"SECUENCIAL_DIARIO" NUMBER
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_614_FK" on "APUNTE_CONTABLE" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_APUNTE_CONTABLE" on "APUNTE_CONTABLE" (
  "SECUENCIA_APUNTE"
 ,"COD_APUNTE_CONTABLE"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_601_FK" on "APUNTE_CONTABLE" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"COD_TIPO_FICHERO" NUMBER NOT NULL
 ,"COD_ENTIDAD_PRESENTADORA" NUMBER NOT NULL
 ,"FECHA_COMIENZO_CICLO" NUMBER(8,0)
 ,"FECHA_CREACION" NUMBER(8,0)
 ,"NOMBRE_FICHERO" VARCHAR2(100)
 ,"DESCRIPCION" VARCHAR2(30)
 ,"ISO_MONEDA" VARCHAR2(3)
 ,"FECHA_INCORPORACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"NUM_CRC" VARCHAR2(30)
 ,"IND_PROCESADO" VARCHAR2(1)
 ,"NUM_ENVIO" VARCHAR2(8)
 ,"IND_6301" VARCHAR2(1) DEFAULT 'N'
 ,"IND_CGPJ" VARCHAR2(1) DEFAULT 'N'
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CONTROL_FICHERO" on "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2052_FK" on "CONTROL_FICHERO" (
  "COD_ENTIDAD_PRESENTADORA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_436_FK" on "CONTROL_FICHERO" (
  "COD_TIPO_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CONTROL_FICHERO_TRABA" (
  "COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"COD_TRABA" NUMBER NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CONTROL_FICHERO_TRABA" on "CONTROL_FICHERO_TRABA" (
  "COD_CONTROL_FICHERO"
 ,"COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "CONTROL_FICHERO_TRABA_FK" on "CONTROL_FICHERO_TRABA" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "CONTROL_FICHERO_TRABA_FK2" on "CONTROL_FICHERO_TRABA" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CUENTA_EMBARGO" (
  "COD_CUENTA_EMBARGO" NUMBER NOT NULL
 ,"COD_EMBARGO" NUMBER NOT NULL
 ,"CUENTA" VARCHAR2(20)
 ,"IMPORTE" NUMBER
 ,"ACTUACION" VARCHAR2(2)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"NUMERO_ORDEN_CUENTA" NUMBER
 ,"CLAVE_SEGURIDAD" VARCHAR2(20)
 ,"IBAN" VARCHAR2(24)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CUENTA_EMBARGO" on "CUENTA_EMBARGO" (
  "COD_CUENTA_EMBARGO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_1897_FK" on "CUENTA_EMBARGO" (
  "COD_EMBARGO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CUENTA_LEVANTAMIENTO" (
  "COD_CUENTA_LEVANTAMIENTO" NUMBER NOT NULL
 ,"COD_LEVANTAMIENTO" NUMBER NOT NULL
 ,"CUENTA" VARCHAR2(20)
 ,"IMPORTE" NUMBER
 ,"ACTUACION" VARCHAR2(2)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"NUMERO_ORDEN_CUENTA" NUMBER
 ,"CAMBIO" NUMBER
 ,"IND_CONTABILIZADO" VARCHAR2(1)
 ,"COD_CONTROL_FICHERO" NUMBER
 ,"IBAN" VARCHAR2(24)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CUENTA_LEVANTAMIENTO" on "CUENTA_LEVANTAMIENTO" (
  "COD_CUENTA_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_1899_FK" on "CUENTA_LEVANTAMIENTO" (
  "COD_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CUENTA_RDB" (
  "NUMERO_CLIENTE" VARCHAR2(10)
 ,"SUBCUENTA" VARCHAR2(2)
 ,"ISO_CODE" VARCHAR2(3)
 ,"FECHA_ALTA" VARCHAR2(8)
 ,"FECHA_BAJA" VARCHAR2(8)
 ,"COMI_APERTURA" VARCHAR2(40)
 ,"INTERES_DEUDOR" VARCHAR2(40)
 ,"INTERES_ACREEDOR" VARCHAR2(40)
 ,"CLAVE_BALANCE" VARCHAR2(6)
 ,"FECHA_INICIO" VARCHAR2(8)
 ,"FECHA_VENCIMIENTO" VARCHAR2(8)
 ,"FECHA_REV_INTERES" VARCHAR2(8)
 ,"PER_REV_INTERES" VARCHAR2(1)
 ,"FECHA_AMORTIZACION" VARCHAR2(8)
 ,"PER_AMORTIZACION" VARCHAR2(1)
 ,"IMPORTE_CREDITO" VARCHAR2(255)
 ,"GARANTIA_CLAVE" VARCHAR2(3)
 ,"GARANTIA_GARANTE" VARCHAR2(20)
 ,"GARANTIA_ISO" VARCHAR2(3)
 ,"GARANTIA_IMPORTE" VARCHAR2(255)
 ,"GARANTIA_PAIS" VARCHAR2(3)
 ,"GARANTIA_GRUPO" VARCHAR2(4)
 ,"GARANTIA_FEC_VTO" VARCHAR2(8)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 696320
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "CUENTA_TRABA" (
  "COD_CUENTA_TRABA" NUMBER NOT NULL
 ,"COD_TRABA" NUMBER NOT NULL
 ,"CUENTA" VARCHAR2(20)
 ,"IMPORTE" NUMBER
 ,"ACTUACION" VARCHAR2(2)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"NUMERO_ORDEN_CUENTA" NUMBER
 ,"COD_ESTADO" NUMBER NOT NULL
 ,"CAMBIO" NUMBER
 ,"IBAN" VARCHAR2(24)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CUENTA_TRABA" on "CUENTA_TRABA" (
  "COD_CUENTA_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_1898_FK" on "CUENTA_TRABA" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2587_FK" on "CUENTA_TRABA" (
  "COD_ESTADO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

-------------------------------------------------------

CREATE TABLE "CUENTAS_INMOVILIZACION" (
  "COD_CUENTA_INMOVILIZACION" NUMBER NOT NULL
 ,"BANCO" VARCHAR2(4)
 ,"SUCURSAL" VARCHAR2(4)
 ,"DC" VARCHAR2(2)
 ,"CUENTA" VARCHAR2(20)
 ,"DESCRIPCION_CUENTA" VARCHAR2(40)
 ,"IND_ACTIVA" VARCHAR2(1)
 ,"ISO_MONEDA" VARCHAR2(3)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_SUCURSAL" NUMBER
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CUENTAS_INMOVILIZACION" on "CUENTAS_INMOVILIZACION" (
  "COD_CUENTA_INMOVILIZACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "CUENTAS_RECAUDACION" (
  "COD_CUENTA_RECAUDACION" NUMBER NOT NULL
 ,"BANCO" VARCHAR2(4)
 ,"SUCURSAL" VARCHAR2(4)
 ,"DC" VARCHAR2(2)
 ,"CUENTA" VARCHAR2(20)
 ,"DESCRIPCION_CUENTA" VARCHAR2(40)
 ,"IND_ACTIVA" VARCHAR2(1)
 ,"ISO_MONEDA" VARCHAR2(3)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_CUENTAS_RECAUDACION" on "CUENTAS_RECAUDACION" (
  "COD_CUENTA_RECAUDACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

---------------------------------------------------------

CREATE TABLE "DATOS_PERSONALES_RDB" (
  "NUMERO_CLIENTE" VARCHAR2(10)
 ,"CLAVE_CORREO" VARCHAR2(3)
 ,"CLAVE_PAIS" VARCHAR2(3)
 ,"CLAVE_CNAE" VARCHAR2(5)
 ,"FECHA_ALTA" VARCHAR2(8)
 ,"FECHA_BAJA" VARCHAR2(8)
 ,"DC_NOMBRE_EMPRESA" VARCHAR2(40)
 ,"DC_OBSERVACIONES" VARCHAR2(40)
 ,"DC_DIRECCION" VARCHAR2(40)
 ,"DC_POBLACION" VARCHAR2(30)
 ,"DC_PAIS_POSTAL" VARCHAR2(2)
 ,"DC_CODIGO_POSTAL" VARCHAR2(5)
 ,"DC_NOMBRE_PAIS" VARCHAR2(32)
 ,"DE_NOMBRE_EMPRESA" VARCHAR2(40)
 ,"DE_OBSERVACIONES" VARCHAR2(40)
 ,"DE_DIRECCION" VARCHAR2(40)
 ,"DE_POBLACION" VARCHAR2(30)
 ,"DE_PAIS_POSTAL" VARCHAR2(2)
 ,"DE_CODIGO_POSTAL" VARCHAR2(5)
 ,"DE_NOMBRE_PAIS" VARCHAR2(32)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 1064960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "DETALLE_CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"NUM_SECUENCIA" NUMBER NOT NULL
 ,"LINEA" CHAR(1048) NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 671375360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "DETALLE_CONTR_PK41024905790039" on "DETALLE_CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
 ,"NUM_SECUENCIA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 7823360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "EMBARGO" (
  "COD_EMBARGO" NUMBER NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"COD_ENTIDAD_ORDENANTE" NUMBER NOT NULL
 ,"NIF" VARCHAR2(9)
 ,"NOMBRE" VARCHAR2(100)
 ,"SIGLAS_VP" VARCHAR2(2)
 ,"NOMBRE_VP" VARCHAR2(25)
 ,"NUMERO" NUMBER
 ,"LETRA" VARCHAR2(1)
 ,"ESCALERA" VARCHAR2(2)
 ,"PISO" VARCHAR2(2)
 ,"PUERTA" VARCHAR2(2)
 ,"MUNICIPIO" VARCHAR2(12)
 ,"CODIGO_POSTAL" VARCHAR2(5)
 ,"NUMERO_EMBARGO" VARCHAR2(40)
 ,"IMPORTE" NUMBER
 ,"FECHA_GENERACION" NUMBER(8,0)
 ,"FECHA_LIMITE_TRABA" NUMBER(8,0)
 ,"ISO_MONEDA" VARCHAR2(3)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_SUCURSAL" NUMBER
 ,"DOMICILIO" VARCHAR2(39)
 ,"TIPO_DEUDA" VARCHAR2(2)
 ,"IND_PROCESADO" CHAR(1)
 ,"DATREGCOMDET" VARCHAR2(200) DEFAULT NULL
 ,"COD_DEUDA_DEUDOR" VARCHAR2(8)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_EMBARGO" on "EMBARGO" (
  "COD_EMBARGO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2054_FK" on "EMBARGO" (
  "COD_ENTIDAD_ORDENANTE"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_586_FK" on "EMBARGO" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ENTIDADES_COMUNICADORAS" (
  "COD_ENTIDAD_PRESENTADORA" NUMBER NOT NULL
 ,"DES_ENTIDAD" VARCHAR2(40)
 ,"NIF_ENTIDAD" VARCHAR2(9)
 ,"IDENTIFICADOR_ENTIDAD" VARCHAR2(2)
 ,"IND_NORMA63" VARCHAR2(1)
 ,"IND_FORMATO_AEAT" VARCHAR2(1)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_CUENTA_RECAUDACION" NUMBER
 ,"PREFIJO_FICHEROS" VARCHAR2(10)
 ,"CODIGO_INE" VARCHAR2(6)
 ,"IND_CGPJ" VARCHAR2(1) DEFAULT 'N'
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_ENTIDADES_COMUNICADORAS" on "ENTIDADES_COMUNICADORAS" (
  "COD_ENTIDAD_PRESENTADORA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2589_FK" on "ENTIDADES_COMUNICADORAS" (
  "COD_CUENTA_RECAUDACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ENTIDADES_ORDENANTES" (
  "COD_ENTIDAD_ORDENANTE" NUMBER NOT NULL
 ,"COD_ENTIDAD_PRESENTADORA" NUMBER NOT NULL
 ,"DES_ENTIDAD" VARCHAR2(40)
 ,"IDENTIFICADOR_ENTIDAD" VARCHAR2(2)
 ,"NIF_ENTIDAD" VARCHAR2(9)
 ,"IND_NORMA63" VARCHAR2(1)
 ,"IND_FORMATO_AEAT" VARCHAR2(1)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"CODIGO_INE" VARCHAR2(6)
 ,"RPT_NOMENT" VARCHAR2(50) DEFAULT NULL
 ,"RPT_DIRENT" VARCHAR2(100) DEFAULT NULL
 ,"RPT_CONENT" VARCHAR2(50) DEFAULT NULL
 ,"RPT_TELENT" VARCHAR2(50) DEFAULT NULL
 ,"IND_CGPJ" VARCHAR2(1) DEFAULT 'N'
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_ENTIDADES_ORDENANTES" on "ENTIDADES_ORDENANTES" (
  "COD_ENTIDAD_ORDENANTE"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2053_FK" on "ENTIDADES_ORDENANTES" (
  "COD_ENTIDAD_PRESENTADORA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

---------------------------------------------------------

CREATE TABLE "ERROR_TRABA" (
  "COD_TRABA" NUMBER NOT NULL
 ,"COD_ERROR" NUMBER NOT NULL
 ,"NUMERO_CAMPO" NUMBER(3,0) NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_ERROR_TRABA" on "ERROR_TRABA" (
  "COD_TRABA"
 ,"COD_ERROR"
 ,"NUMERO_CAMPO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "ERROR_TRABA_FK" on "ERROR_TRABA" (
  "COD_ERROR"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "ERROR_TRABA_FK2" on "ERROR_TRABA" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

-------------------------------------

CREATE TABLE "ERRORES" (
  "COD_ERROR" NUMBER NOT NULL
 ,"NUMERO_ERROR" VARCHAR2(3)
 ,"DESCRIPCION_ERROR" VARCHAR2(240)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_ERRORES" on "ERRORES" (
  "COD_ERROR"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ESTADO_INT_CANCELACION" (
  "COD_ESTADO_INT_CANCELACION" NUMBER NOT NULL
 ,"DES_ESTADO_INT_CANCELACION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_INT_CANCELACION_PK" on "ESTADO_INT_CANCELACION" (
  "COD_ESTADO_INT_CANCELACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ESTADO_INT_EJECUCION" (
  "COD_ESTADO_INT_EJECUCION" NUMBER NOT NULL
 ,"DES_ESTADO_INT_EJECUCION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_INT_EJECUCION_PK" on "ESTADO_INT_EJECUCION" (
  "COD_ESTADO_INT_EJECUCION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ESTADO_INT_LEVANTAMIENTO" (
  "COD_ESTADO_INT_LEVANTAMIENTO" NUMBER NOT NULL
 ,"DES_ESTADO_INT_LEVANTAMIENTO" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_INT_LEVANTAMIENTO_PK" on "ESTADO_INT_LEVANTAMIENTO" (
  "COD_ESTADO_INT_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ESTADO_INT_PETICION" (
  "COD_ESTADO_INT_PETICION" NUMBER NOT NULL
 ,"DES_ESTADO_INT_PETICION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_INTERNO_PETICION_PK" on "ESTADO_INT_PETICION" (
  "COD_ESTADO_INT_PETICION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


----------------------------------------------------

CREATE TABLE "ESTADO_INT_TRABA" (
  "COD_ESTADO_INT_TRABA" NUMBER NOT NULL
 ,"DES_ESTADO_INT_TRABA" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_INT_TRABA_PK" on "ESTADO_INT_TRABA" (
  "COD_ESTADO_INT_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "ESTADO_PRIMARIO_PETICION" (
  "COD_ESTADO_PRIMARIO_PETICION" VARCHAR2(4) NOT NULL
 ,"DES_ESTADO_PRIMARIO_PETICION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_PRIMARIO_PETICION_PK" on "ESTADO_PRIMARIO_PETICION" (
  "COD_ESTADO_PRIMARIO_PETICION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "ESTADO_PRIMARIO_RESP" (
  "COD_ESTADO_PRIMARIO_RESP" VARCHAR2(4) NOT NULL
 ,"DES_ESTADO_PRIMARIO_RESP" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_PRIMARIO_RESP_PK" on "ESTADO_PRIMARIO_RESP" (
  "COD_ESTADO_PRIMARIO_RESP"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "ESTADO_RESP_EJECUCION" (
  "COD_ESTADO_RESP_EJECUCION" VARCHAR2(4) NOT NULL
 ,"DES_ESTADO_RESP_EJECUCION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_RESP_EJECUCION_PK" on "ESTADO_RESP_EJECUCION" (
  "COD_ESTADO_RESP_EJECUCION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "ESTADO_RESP_LEVANTAMIENTO" (
  "COD_ESTADO_RESP_LEVANTAMIENTO" VARCHAR2(4) NOT NULL
 ,"DES_ESTADO_RESP_LEVANTAMIENTO" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_RESP_LEVANTAMIENTO_PK" on "ESTADO_RESP_LEVANTAMIENTO" (
  "COD_ESTADO_RESP_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "ESTADO_RESP_TRABA" (
  "COD_ESTADO_RESP_TRABA" VARCHAR2(4) NOT NULL
 ,"DES_ESTADO_RESP_TRABA" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_RESP_TRABA_PK" on "ESTADO_RESP_TRABA" (
  "COD_ESTADO_RESP_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

----------------------------------------------------

CREATE TABLE "ESTADO_SECUNDARIO_RESP" (
  "COD_ESTADO_SECUNDARIO_RESP" VARCHAR2(16) NOT NULL
 ,"DES_ESTADO_SECUNDARIO_RESP" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "ESTADO_SECUNDARIO_RESP_PK" on "ESTADO_SECUNDARIO_RESP" (
  "COD_ESTADO_SECUNDARIO_RESP"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "ESTADO_TRABA" (
  "COD_ESTADO" NUMBER NOT NULL
 ,"DES_ESTADO" VARCHAR2(40)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_ESTADO_TRABA" on "ESTADO_TRABA" (
  "COD_ESTADO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "FICHERO_FINAL" (
  "COD_FICHERO_FINAL" NUMBER NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"IMPORTE" NUMBER NOT NULL
 ,"F_VALOR" NUMBER(14,0) NOT NULL
 ,"COD_FICHERO_DILIGENCIAS" NUMBER NOT NULL
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0) NOT NULL
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(20) NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "SYS_C0012068" on "FICHERO_FINAL" (
  "COD_FICHERO_FINAL"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/



--------------------------------------

CREATE TABLE "HISTORIAL_ESTADO_TRABA" (
  "COD_TRABA" NUMBER NOT NULL
 ,"SECUENCIA_ESTADO" NUMBER NOT NULL
 ,"COD_ESTADO" NUMBER NOT NULL
 ,"FECHA_ESTADO" NUMBER(14,0)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_HISTORIAL_ESTADO_TRABA" on "HISTORIAL_ESTADO_TRABA" (
  "COD_TRABA"
 ,"SECUENCIA_ESTADO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_610_FK" on "HISTORIAL_ESTADO_TRABA" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_611_FK" on "HISTORIAL_ESTADO_TRABA" (
  "COD_ESTADO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "LEVANTAMIENTO_TRABA" (
  "COD_LEVANTAMIENTO" NUMBER NOT NULL
 ,"COD_TRABA" NUMBER NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"ESTADO_CONTABLE" NUMBER
 ,"ESTADO_EJECUTADO" NUMBER
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"COD_DEUDA_DEUDOR" VARCHAR2(8)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_LEVANTAMIENTO_TRABA" on "LEVANTAMIENTO_TRABA" (
  "COD_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_204_FK" on "LEVANTAMIENTO_TRABA" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_588_FK" on "LEVANTAMIENTO_TRABA" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

-------------------------------------

CREATE TABLE "MONEDAS_RDB" (
  "ISO" VARCHAR2(3)
 ,"ISO_IBS" VARCHAR2(3)
 ,"DESCRIPCION" VARCHAR2(20)
 ,"BASE" NUMBER(5,0)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------


CREATE TABLE "PAISES_IBS_RDB" (
  "PAIS" VARCHAR2(3)
 ,"NOMBRE" VARCHAR2(35)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "PAISES_RDB_RDB" (
  "CODIGO_PAIS" VARCHAR2(3)
 ,"ISO_CODE" VARCHAR2(3)
 ,"CODIGO_PAIS_BE" VARCHAR2(4)
 ,"DESCRIPCION" VARCHAR2(35)
 ,"TIPO_PAIS" VARCHAR2(1)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "PETICION_INFORMACION" (
  "COD_PETICION" CHAR(10) NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER
 ,"NIF" VARCHAR2(9)
 ,"RAZON_SOCIAL" VARCHAR2(40)
 ,"DOMICILIO" VARCHAR2(39)
 ,"MUNICIPIO" VARCHAR2(12)
 ,"CODIGO_POSTAL" VARCHAR2(5)
 ,"NUMERO_EMBARGO" VARCHAR2(13)
 ,"CUENTA1" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD1" VARCHAR2(12)
 ,"CUENTA2" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD2" VARCHAR2(12)
 ,"CUENTA3" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD3" VARCHAR2(20)
 ,"IND_INFORMACION_CORRECTA" VARCHAR2(1)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_ENTIDAD_ORDENANTE" NUMBER NOT NULL
 ,"TIPO_DEUDA" VARCHAR2(2)
 ,"IND_MAS_CUENTAS" VARCHAR2(1)
 ,"COD_SUCURSAL" NUMBER
 ,"COD_FICHERO_RESPUESTA" NUMBER
 ,"CUENTA4" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD4" VARCHAR2(12)
 ,"CUENTA5" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD5" VARCHAR2(12)
 ,"CUENTA6" VARCHAR2(20)
 ,"CLAVE_SEGURIDAD6" VARCHAR2(12)
 ,"IBAN1" VARCHAR2(24)
 ,"IBAN2" VARCHAR2(24)
 ,"IBAN3" VARCHAR2(24)
 ,"IBAN4" VARCHAR2(24)
 ,"IBAN5" VARCHAR2(24)
 ,"IBAN6" VARCHAR2(24)
 ,"COD_DEUDA_DEUDOR" VARCHAR2(8)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_2232_FK" on "PETICION_INFORMACION" (
  "COD_CONTROL_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_PETICION_INFORMACION" on "PETICION_INFORMACION" (
  "COD_PETICION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "PETICIONES" (
  "COD_PETICION" VARCHAR2(16) NOT NULL
 ,"NUM_ELEMENTOS" NUMBER
 ,"TIMESTAMP" VARCHAR2(29)
 ,"COD_ESTADO_PRIMARIO_PETICION" VARCHAR2(4)
 ,"COD_ESTADO_PRIMARIO_RESP" VARCHAR2(4)
 ,"ESTADO_SECUNDARIO_PETICION" VARCHAR2(16)
 ,"COD_ESTADO_SECUNDARIO_RESP" VARCHAR2(16)
 ,"LITERAL_ERROR" VARCHAR2(255)
 ,"TIEMPO_ESTIMADO_RESPUESTA" NUMBER
 ,"COD_CONTROL_FICHERO" NUMBER
 ,"COD_ESTADO_INT_PETICION" NUMBER
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PETICIONES_PK" on "PETICIONES" (
  "COD_PETICION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "SEMAFORO" (
  "FECHA" NUMBER(14,0)
 ,"USUARIO" VARCHAR2(25)
 ,"MAQUINA" VARCHAR2(25)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "SEMAFORO_CGPJ" (
  "FECHA" NUMBER(14,0) NOT NULL
 ,"USUARIO" NVARCHAR2(50) NOT NULL
 ,"MAQUINA" NVARCHAR2(50) NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "SOLICITUDES_CANCELACION" (
  "COD_SOLICITUD_CANCELACION" VARCHAR2(40) NOT NULL
 ,"COD_PETICION" VARCHAR2(16)
 ,"COD_ESTADO_INT_CANCELACION" NUMBER
 ,"NIF_EMISOR" VARCHAR2(10)
 ,"NOMBRE_EMISOR" VARCHAR2(50)
 ,"IDENTIFICADOR_SOLICITANTE" VARCHAR2(10)
 ,"NOMBRE_SOLICITANTE" VARCHAR2(50)
 ,"FINALIDAD" VARCHAR2(250)
 ,"CONSENTIMIENTO" VARCHAR2(20)
 ,"NOMBRE_COMPLETO_FUNCIONARIO" VARCHAR2(122)
 ,"NIF_FUNCIONARIO" VARCHAR2(10)
 ,"COD_TIPO_DOCUMENTACION" NUMBER
 ,"DOCUMENTACION" VARCHAR2(14)
 ,"NOMBRE_COMPLETO_TITULAR" VARCHAR2(122)
 ,"NOMBRE_TITULAR" VARCHAR2(40)
 ,"APELLIDO1_TITULAR" VARCHAR2(40)
 ,"APELLIDO2_TITULAR" VARCHAR2(40)
 ,"CODIGO_CERTIFICADO" VARCHAR2(64)
 ,"ID_TRANSMISION" VARCHAR2(26)
 ,"FECHA_GENERACION" VARCHAR2(29)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"COD_SOLICITUD_A_CANCELAR" VARCHAR2(40)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "SOLICITUDES_CANCELACION_PK" on "SOLICITUDES_CANCELACION" (
  "COD_SOLICITUD_CANCELACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "SOLICITUDES_EJECUCION" (
  "COD_SOLICITUD_EJECUCION" VARCHAR2(40) NOT NULL
 ,"COD_PETICION" VARCHAR2(16)
 ,"COD_TRABA" NUMBER
 ,"COD_ESTADO_INT_EJECUCION" NUMBER
 ,"COD_ESTADO_RESP_EJECUCION" VARCHAR2(4)
 ,"ORDENANTE" VARCHAR2(70)
 ,"ID_ORDENANTE" VARCHAR2(14)
 ,"IBAN" VARCHAR2(24)
 ,"CONCEPTO" VARCHAR2(140)
 ,"BENEFICIARIO" VARCHAR2(70)
 ,"BIC" VARCHAR2(11)
 ,"TIPOTR" VARCHAR2(4)
 ,"PROPOSITOTR" VARCHAR2(4)
 ,"IMPORTE_SOLICITUD" VARCHAR2(13)
 ,"IMPORTE_RESPUESTA" VARCHAR2(13)
 ,"NIF_EMISOR" VARCHAR2(10)
 ,"NOMBRE_EMISOR" VARCHAR2(50)
 ,"IDENTIFICADOR_SOLICITANTE" VARCHAR2(10)
 ,"NOMBRE_SOLICITANTE" VARCHAR2(50)
 ,"FINALIDAD" VARCHAR2(250)
 ,"CONSENTIMIENTO" VARCHAR2(20)
 ,"NOMBRE_COMPLETO_FUNCIONARIO" VARCHAR2(122)
 ,"NIF_FUNCIONARIO" VARCHAR2(10)
 ,"COD_TIPO_DOCUMENTACION" NUMBER
 ,"DOCUMENTACION" VARCHAR2(14)
 ,"NOMBRE_COMPLETO_TITULAR" VARCHAR2(122)
 ,"NOMBRE_TITULAR" VARCHAR2(40)
 ,"APELLIDO1_TITULAR" VARCHAR2(40)
 ,"APELLIDO2_TITULAR" VARCHAR2(40)
 ,"CODIGO_CERTIFICADO" VARCHAR2(64)
 ,"ID_TRANSMISION" VARCHAR2(26)
 ,"FECHA_GENERACION" VARCHAR2(29)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "SOLICITUDES_EJECUCION_PK" on "SOLICITUDES_EJECUCION" (
  "COD_SOLICITUD_EJECUCION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "SOLICITUDES_LEVANTAMIENTO" (
  "COD_SOLICITUD_LEVANTAMIENTO" VARCHAR2(40) NOT NULL
 ,"COD_PETICION" VARCHAR2(16)
 ,"COD_TRABA" NUMBER
 ,"COD_ESTADO_INT_LEVANTAMIENTO" NUMBER
 ,"COD_ESTADO_RESP_LEVANTAMIENTO" VARCHAR2(4)
 ,"IMPORTE_SOLICITUD" VARCHAR2(13)
 ,"IMPORTE_RESPUESTA" VARCHAR2(13)
 ,"NIF_EMISOR" VARCHAR2(10)
 ,"NOMBRE_EMISOR" VARCHAR2(50)
 ,"IDENTIFICADOR_SOLICITANTE" VARCHAR2(10)
 ,"NOMBRE_SOLICITANTE" VARCHAR2(50)
 ,"FINALIDAD" VARCHAR2(250)
 ,"CONSENTIMIENTO" VARCHAR2(20)
 ,"NOMBRE_COMPLETO_FUNCIONARIO" VARCHAR2(122)
 ,"NIF_FUNCIONARIO" VARCHAR2(10)
 ,"COD_TIPO_DOCUMENTACION" NUMBER
 ,"DOCUMENTACION" VARCHAR2(14)
 ,"NOMBRE_COMPLETO_TITULAR" VARCHAR2(122)
 ,"NOMBRE_TITULAR" VARCHAR2(40)
 ,"APELLIDO1_TITULAR" VARCHAR2(40)
 ,"APELLIDO2_TITULAR" VARCHAR2(40)
 ,"CODIGO_CERTIFICADO" VARCHAR2(64)
 ,"ID_TRANSMISION" VARCHAR2(26)
 ,"FECHA_GENERACION" VARCHAR2(29)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"INTERVENCION_USUARIO" VARCHAR2(1) DEFAULT 'N'
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "SOLICITUDES_LEVANTAMIENTO_PK" on "SOLICITUDES_LEVANTAMIENTO" (
  "COD_SOLICITUD_LEVANTAMIENTO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "SOLICITUDES_TRABA" (
  "COD_SOLICITUD_TRABA" VARCHAR2(40) NOT NULL
 ,"COD_PETICION" VARCHAR2(16)
 ,"COD_TRABA" NUMBER
 ,"COD_ESTADO_INT_TRABA" NUMBER
 ,"COD_ESTADO_RESP_TRABA" VARCHAR2(4)
 ,"IMPORTE_SOLICITUD" VARCHAR2(13)
 ,"IMPORTE_RESPUESTA" VARCHAR2(13)
 ,"TIENE_POSICIONES" VARCHAR2(1)
 ,"NIF_EMISOR" VARCHAR2(10)
 ,"NOMBRE_EMISOR" VARCHAR2(50)
 ,"IDENTIFICADOR_SOLICITANTE" VARCHAR2(10)
 ,"NOMBRE_SOLICITANTE" VARCHAR2(50)
 ,"FINALIDAD" VARCHAR2(250)
 ,"CONSENTIMIENTO" VARCHAR2(20)
 ,"NOMBRE_COMPLETO_FUNCIONARIO" VARCHAR2(122)
 ,"NIF_FUNCIONARIO" VARCHAR2(10)
 ,"COD_TIPO_DOCUMENTACION" NUMBER
 ,"DOCUMENTACION" VARCHAR2(14)
 ,"NOMBRE_COMPLETO_TITULAR" VARCHAR2(122)
 ,"NOMBRE_TITULAR" VARCHAR2(40)
 ,"APELLIDO1_TITULAR" VARCHAR2(40)
 ,"APELLIDO2_TITULAR" VARCHAR2(40)
 ,"CODIGO_CERTIFICADO" VARCHAR2(64)
 ,"ID_TRANSMISION" VARCHAR2(26)
 ,"FECHA_GENERACION" VARCHAR2(29)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "SOLICITUDES_TRABA_PK" on "SOLICITUDES_TRABA" (
  "COD_SOLICITUD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "TAREAS_PENDIENTES" (
  "COD_TAREA_PENDIENTE" NUMBER NOT NULL
 ,"DESCRIPCION" VARCHAR2(200)
 ,"FECHA_TOPE_REALIZACION" NUMBER(14,0)
 ,"FECHA_INICIO_AVISO" NUMBER(14,0)
 ,"FECHA_EFECTIVA_REALIZACION" NUMBER(14,0)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_SUCURSAL" NUMBER
 ,"COD_CONTROL_FICHERO" NUMBER
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_TAREAS_PENDIENTES" on "TAREAS_PENDIENTES" (
  "COD_TAREA_PENDIENTE"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "TAREAS_REALIZADAS" (
  "COD_TAREA_REALIZADA" NUMBER NOT NULL
 ,"FECHA_TOPE_REALIZACION" NUMBER(14,0)
 ,"FECHA_EFECTIVA_REALIZACION" NUMBER(14,0)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"FECHA_INICIO_AVISO" NUMBER(14,0)
 ,"DESCRIPCION" VARCHAR2(200)
 ,"COD_SUCURSAL" NUMBER
 ,"COD_CONTROL_FICHERO" NUMBER
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_TAREAS_REALIZADAS" on "TAREAS_REALIZADAS" (
  "COD_TAREA_REALIZADA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION" NUMBER NOT NULL
 ,"DES_TIPO_DOCUMENTACION" VARCHAR2(60)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "TIPO_DOCUMENTACION_PK" on "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


--------------------------------------

CREATE TABLE "TIPO_FICHERO" (
  "COD_TIPO_FICHERO" NUMBER NOT NULL
 ,"DES_TIPO_FICHERO" VARCHAR2(70)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_TIPO_FICHERO" on "TIPO_FICHERO" (
  "COD_TIPO_FICHERO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/



--------------------------------------

CREATE TABLE "TITULARES_RDB" (
  "NUMERO_CLIENTE" VARCHAR2(10)
 ,"NUMERO_TITULAR" VARCHAR2(1)
 ,"APELLIDO_EMPRESA" VARCHAR2(30)
 ,"PAIS_NIF" VARCHAR2(2)
 ,"NIF" VARCHAR2(9)
 ,"NOMBRE" VARCHAR2(20)
 ,"DIRECCION" VARCHAR2(40)
 ,"POBLACION" VARCHAR2(30)
 ,"PAIS_POSTAL" VARCHAR2(2)
 ,"CODIGO_POSTAL" VARCHAR2(5)
 ,"NOMBRE_PAIS" VARCHAR2(20)
 ,"TIPO_CLIENTE" VARCHAR2(1)
 ,"CLAVE_PERCEPTOR" VARCHAR2(1)
 ,"NUMERO_NIE" VARCHAR2(22)
 ,"NUMERO_NIE_ANT" VARCHAR2(22)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 696320
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

--------------------------------------

CREATE TABLE "TRABAS" (
  "COD_TRABA" NUMBER NOT NULL
 ,"COD_EMBARGO" NUMBER NOT NULL
 ,"COD_CUENTA_RECAUDACION" NUMBER NOT NULL
 ,"COD_CUENTA_INMOVILIZACION" NUMBER NOT NULL
 ,"IMPORTE_TRABADO" NUMBER
 ,"FECHA_TRABA" NUMBER(8,0)
 ,"IND_MAS_CUENTAS" NUMBER
 ,"FECHA_LIMITE" NUMBER(14,0)
 ,"IND_MODIFICADO" VARCHAR2(1)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"COD_ESTADO" NUMBER NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "TRABA_C_RECAUDACION_FK" on "TRABAS" (
  "COD_CUENTA_RECAUDACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE UNIQUE INDEX "PK_TRABAS" on "TRABAS" (
  "COD_TRABA"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "COD_ESTADO_ACTUAL_FK" on "TRABAS" (
  "COD_ESTADO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "RELATION_102_FK" on "TRABAS" (
  "COD_EMBARGO"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

CREATE INDEX "TRABA_C_INMOVILIZACION_FK" on "TRABAS" (
  "COD_CUENTA_INMOVILIZACION"
)
TABLESPACE "EMBARGOS2_INDEX"
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/


ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "PK_APUNTE_CONTABLE"
PRIMARY KEY (
  "SECUENCIA_APUNTE"
 ,"COD_APUNTE_CONTABLE"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "SYS_C002477"
CHECK (COD_CONTROL_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "SYS_C002476"
CHECK (COD_APUNTE_CONTABLE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "SYS_C002475"
CHECK (SECUENCIA_APUNTE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "PK_CONTROL_FICHERO"
PRIMARY KEY (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "SYS_C002454"
CHECK (COD_CONTROL_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "SYS_C002455"
CHECK (COD_TIPO_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "SYS_C002456"
CHECK (COD_ENTIDAD_PRESENTADORA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "CONTROL_FICHERO_TRABA" ADD CONSTRAINT "PK_CONTROL_FICHERO_TRABA"
PRIMARY KEY (
  "COD_CONTROL_FICHERO"
 ,"COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO_TRABA" ADD CONSTRAINT "SYS_C002499"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO_TRABA" ADD CONSTRAINT "SYS_C002498"
CHECK (COD_CONTROL_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "CUENTA_EMBARGO" ADD CONSTRAINT "PK_CUENTA_EMBARGO"
PRIMARY KEY (
  "COD_CUENTA_EMBARGO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_EMBARGO" ADD CONSTRAINT "SYS_C002483"
CHECK (COD_CUENTA_EMBARGO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_EMBARGO" ADD CONSTRAINT "SYS_C002484"
CHECK (COD_EMBARGO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "CUENTA_LEVANTAMIENTO" ADD CONSTRAINT "PK_CUENTA_LEVANTAMIENTO"
PRIMARY KEY (
  "COD_CUENTA_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_LEVANTAMIENTO" ADD CONSTRAINT "SYS_C002490"
CHECK (COD_CUENTA_LEVANTAMIENTO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_LEVANTAMIENTO" ADD CONSTRAINT "SYS_C002491"
CHECK (COD_LEVANTAMIENTO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "PK_CUENTA_TRABA"
PRIMARY KEY (
  "COD_CUENTA_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "SYS_C002486"
CHECK (COD_CUENTA_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "SYS_C002487"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "SYS_C002488"
CHECK (COD_ESTADO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "CUENTAS_INMOVILIZACION" ADD CONSTRAINT "PK_CUENTAS_INMOVILIZACION"
PRIMARY KEY (
  "COD_CUENTA_INMOVILIZACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTAS_INMOVILIZACION" ADD CONSTRAINT "SYS_C002444"
CHECK (COD_CUENTA_INMOVILIZACION IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTAS_RECAUDACION" ADD CONSTRAINT "PK_CUENTAS_RECAUDACION"
PRIMARY KEY (
  "COD_CUENTA_RECAUDACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTAS_RECAUDACION" ADD CONSTRAINT "SYS_C002446"
CHECK (COD_CUENTA_RECAUDACION IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "DETALLE_CONTROL_FICHERO" ADD CONSTRAINT "DETALLE_CONTR_PK41024905790039"
PRIMARY KEY (
  "COD_CONTROL_FICHERO"
 ,"NUM_SECUENCIA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "EMBARGO" ADD CONSTRAINT "PK_EMBARGO"
PRIMARY KEY (
  "COD_EMBARGO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "EMBARGO" ADD CONSTRAINT "SYS_C002461"
CHECK (COD_EMBARGO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "EMBARGO" ADD CONSTRAINT "SYS_C002462"
CHECK (COD_CONTROL_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "EMBARGO" ADD CONSTRAINT "SYS_C002463"
CHECK (COD_ENTIDAD_ORDENANTE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/




ALTER TABLE "ENTIDADES_COMUNICADORAS" ADD CONSTRAINT "PK_ENTIDADES_COMUNICADORAS"
PRIMARY KEY (
  "COD_ENTIDAD_PRESENTADORA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ENTIDADES_COMUNICADORAS" ADD CONSTRAINT "SYS_C002452"
CHECK (COD_ENTIDAD_PRESENTADORA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "ENTIDADES_ORDENANTES" ADD CONSTRAINT "PK_ENTIDADES_ORDENANTES"
PRIMARY KEY (
  "COD_ENTIDAD_ORDENANTE"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ENTIDADES_ORDENANTES" ADD CONSTRAINT "SYS_C002458"
CHECK (COD_ENTIDAD_ORDENANTE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ENTIDADES_ORDENANTES" ADD CONSTRAINT "SYS_C002459"
CHECK (COD_ENTIDAD_PRESENTADORA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "SYS_C002495"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "SYS_C002496"
CHECK (COD_ERROR IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "SYS_C002977"
CHECK (NUMERO_CAMPO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERRORES" ADD CONSTRAINT "PK_ERRORES"
PRIMARY KEY (
  "COD_ERROR"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERRORES" ADD CONSTRAINT "SYS_C002442"
CHECK (COD_ERROR IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_INT_CANCELACION" ADD CONSTRAINT "ESTADO_INT_CANCELACION_PK"
PRIMARY KEY (
  "COD_ESTADO_INT_CANCELACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_INT_EJECUCION" ADD CONSTRAINT "ESTADO_INT_EJECUCION_PK"
PRIMARY KEY (
  "COD_ESTADO_INT_EJECUCION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_INT_LEVANTAMIENTO" ADD CONSTRAINT "ESTADO_INT_LEVANTAMIENTO_PK"
PRIMARY KEY (
  "COD_ESTADO_INT_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_INT_PETICION" ADD CONSTRAINT "ESTADO_INTERNO_PETICION_PK"
PRIMARY KEY (
  "COD_ESTADO_INT_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_INT_TRABA" ADD CONSTRAINT "ESTADO_INT_TRABA_PK"
PRIMARY KEY (
  "COD_ESTADO_INT_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_PRIMARIO_PETICION" ADD CONSTRAINT "ESTADO_PRIMARIO_PETICION_PK"
PRIMARY KEY (
  "COD_ESTADO_PRIMARIO_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_PRIMARIO_RESP" ADD CONSTRAINT "ESTADO_PRIMARIO_RESP_PK"
PRIMARY KEY (
  "COD_ESTADO_PRIMARIO_RESP"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_RESP_EJECUCION" ADD CONSTRAINT "ESTADO_RESP_EJECUCION_PK"
PRIMARY KEY (
  "COD_ESTADO_RESP_EJECUCION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_RESP_LEVANTAMIENTO" ADD CONSTRAINT "ESTADO_RESP_LEVANTAMIENTO_PK"
PRIMARY KEY (
  "COD_ESTADO_RESP_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_RESP_TRABA" ADD CONSTRAINT "ESTADO_RESP_TRABA_PK"
PRIMARY KEY (
  "COD_ESTADO_RESP_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_SECUNDARIO_RESP" ADD CONSTRAINT "ESTADO_SECUNDARIO_RESP_PK"
PRIMARY KEY (
  "COD_ESTADO_SECUNDARIO_RESP"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_TRABA" ADD CONSTRAINT "PK_ESTADO_TRABA"
PRIMARY KEY (
  "COD_ESTADO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_TRABA" ADD CONSTRAINT "SYS_C002450"
CHECK (COD_ESTADO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "FICHERO_FINAL" ADD
PRIMARY KEY (
  "COD_FICHERO_FINAL"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "PK_HISTORIAL_ESTADO_TRABA"
PRIMARY KEY (
  "COD_TRABA"
 ,"SECUENCIA_ESTADO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "SYS_C002479"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "SYS_C002480"
CHECK (SECUENCIA_ESTADO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "SYS_C002481"
CHECK (COD_ESTADO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "PK_LEVANTAMIENTO_TRABA"
PRIMARY KEY (
  "COD_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "SYS_C002472"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "SYS_C002471"
CHECK (COD_LEVANTAMIENTO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "SYS_C002473"
CHECK (COD_CONTROL_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "PK_PETICION_INFORMACION"
PRIMARY KEY (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "SYS_C002493"
CHECK (COD_PETICION IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "SYS_C002530"
CHECK (COD_ENTIDAD_ORDENANTE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_PK"
PRIMARY KEY (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "SOLICITUDES_CANCELACION" ADD CONSTRAINT "SOLICITUDES_CANCELACION_PK"
PRIMARY KEY (
  "COD_SOLICITUD_CANCELACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_EJECUCION" ADD CONSTRAINT "SOLICITUDES_EJECUCION_PK"
PRIMARY KEY (
  "COD_SOLICITUD_EJECUCION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_LEVANTAMIENTO" ADD CONSTRAINT "SOLICITUDES_LEVANTAMIENTO_PK"
PRIMARY KEY (
  "COD_SOLICITUD_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_TRABA" ADD CONSTRAINT "SOLICITUDES_TRABA_PK"
PRIMARY KEY (
  "COD_SOLICITUD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "TAREAS_PENDIENTES" ADD CONSTRAINT "PK_TAREAS_PENDIENTES"
PRIMARY KEY (
  "COD_TAREA_PENDIENTE"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TAREAS_PENDIENTES" ADD CONSTRAINT "SYS_C002440"
CHECK (COD_TAREA_PENDIENTE IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TAREAS_REALIZADAS" ADD CONSTRAINT "PK_TAREAS_REALIZADAS"
PRIMARY KEY (
  "COD_TAREA_REALIZADA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TAREAS_REALIZADAS" ADD CONSTRAINT "SYS_C002438"
CHECK (COD_TAREA_REALIZADA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/



ALTER TABLE "TIPO_DOCUMENTACION" ADD CONSTRAINT "TIPO_DOCUMENTACION_PK"
PRIMARY KEY (
  "COD_TIPO_DOCUMENTACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TIPO_FICHERO" ADD CONSTRAINT "PK_TIPO_FICHERO"
PRIMARY KEY (
  "COD_TIPO_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TIPO_FICHERO" ADD CONSTRAINT "SYS_C002448"
CHECK (COD_TIPO_FICHERO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "PK_TRABAS"
PRIMARY KEY (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "SYS_C002465"
CHECK (COD_TRABA IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "SYS_C002466"
CHECK (COD_EMBARGO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "SYS_C002467"
CHECK (COD_CUENTA_RECAUDACION IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "SYS_C002468"
CHECK (COD_CUENTA_INMOVILIZACION IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "SYS_C002469"
CHECK (COD_ESTADO IS NOT NULL)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "FK_APUNTE_C_RELATION__CONTROL_"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "APUNTE_CONTABLE" ADD CONSTRAINT "FK_APUNTE_C_RELATION__TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "FK_CONTROL__RELATION__TIPO_FIC"
FOREIGN KEY (
  "COD_TIPO_FICHERO"
)
REFERENCES "TIPO_FICHERO" (
  "COD_TIPO_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO" ADD CONSTRAINT "FK_CONTROL__RELATION__ENTIDADE"
FOREIGN KEY (
  "COD_ENTIDAD_PRESENTADORA"
)
REFERENCES "ENTIDADES_COMUNICADORAS" (
  "COD_ENTIDAD_PRESENTADORA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO_TRABA" ADD CONSTRAINT "FK_CONTROL__CONTROL_F_CONTROL_"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CONTROL_FICHERO_TRABA" ADD CONSTRAINT "FK_CONTROL__CONTROL_F_TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_EMBARGO" ADD CONSTRAINT "FK_CUENTA_E_RELATION__EMBARGO"
FOREIGN KEY (
  "COD_EMBARGO"
)
REFERENCES "EMBARGO" (
  "COD_EMBARGO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_LEVANTAMIENTO" ADD CONSTRAINT "FK_CUENTA_L_RELATION__LEVANTAM"
FOREIGN KEY (
  "COD_LEVANTAMIENTO"
)
REFERENCES "LEVANTAMIENTO_TRABA" (
  "COD_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "FK_CUENTA_T_RELATION__TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "CUENTA_TRABA" ADD CONSTRAINT "FK_CUENTA_T_RELATION__ESTADO_T"
FOREIGN KEY (
  "COD_ESTADO"
)
REFERENCES "ESTADO_TRABA" (
  "COD_ESTADO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "DETALLE_CONTROL_FICHERO" ADD CONSTRAINT "DETALLE_CONTR_FK61024905808615"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "EMBARGO" ADD CONSTRAINT "FK_EMBARGO_RELATION__CONTROL_"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "EMBARGO" ADD CONSTRAINT "FK_EMBARGO_RELATION__ENTIDADE"
FOREIGN KEY (
  "COD_ENTIDAD_ORDENANTE"
)
REFERENCES "ENTIDADES_ORDENANTES" (
  "COD_ENTIDAD_ORDENANTE"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ENTIDADES_COMUNICADORAS" ADD CONSTRAINT "FK_ENTIDADE_RELATION__CUENTAS_"
FOREIGN KEY (
  "COD_CUENTA_RECAUDACION"
)
REFERENCES "CUENTAS_RECAUDACION" (
  "COD_CUENTA_RECAUDACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ENTIDADES_ORDENANTES" ADD CONSTRAINT "FK_ENTIDADE_RELATION__ENTIDADE"
FOREIGN KEY (
  "COD_ENTIDAD_PRESENTADORA"
)
REFERENCES "ENTIDADES_COMUNICADORAS" (
  "COD_ENTIDAD_PRESENTADORA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "FK_ERROR_TR_ERROR_TRA_TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "FK_ERROR_TR_ERROR_TRA_ERRORES"
FOREIGN KEY (
  "COD_ERROR"
)
REFERENCES "ERRORES" (
  "COD_ERROR"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ERROR_TRABA" ADD CONSTRAINT "FK_ERROR_TR_CONTROL_FICHERO"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "FICHERO_FINAL" ADD
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "FK_HISTORIA_RELATION__TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "HISTORIAL_ESTADO_TRABA" ADD CONSTRAINT "FK_HISTORIA_RELATION__ESTADO_T"
FOREIGN KEY (
  "COD_ESTADO"
)
REFERENCES "ESTADO_TRABA" (
  "COD_ESTADO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "FK_LEVANTAM_RELATION__TRABAS"
FOREIGN KEY (
  "COD_TRABA"
)
REFERENCES "TRABAS" (
  "COD_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "FK_LEVANTAM_RELATION__CONTROL_"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "FK_PETICION_RELATION__CONTROL_"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "FK_PETICION_RELATION_ORDENANTE"
FOREIGN KEY (
  "COD_ENTIDAD_ORDENANTE"
)
REFERENCES "ENTIDADES_ORDENANTES" (
  "COD_ENTIDAD_ORDENANTE"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_CONTROL_FICHERO_FK"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_ESTADO_INT_FK"
FOREIGN KEY (
  "COD_ESTADO_INT_PETICION"
)
REFERENCES "ESTADO_INT_PETICION" (
  "COD_ESTADO_INT_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_ESTADO_PRIM_FK"
FOREIGN KEY (
  "COD_ESTADO_PRIMARIO_PETICION"
)
REFERENCES "ESTADO_PRIMARIO_PETICION" (
  "COD_ESTADO_PRIMARIO_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_ESTADO_RESP_FK"
FOREIGN KEY (
  "COD_ESTADO_PRIMARIO_RESP"
)
REFERENCES "ESTADO_PRIMARIO_RESP" (
  "COD_ESTADO_PRIMARIO_RESP"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICIONES" ADD CONSTRAINT "PETICIONES_ESTADO_SEC_RESP_FK"
FOREIGN KEY (
  "COD_ESTADO_SECUNDARIO_RESP"
)
REFERENCES "ESTADO_SECUNDARIO_RESP" (
  "COD_ESTADO_SECUNDARIO_RESP"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_CANCELACION" ADD CONSTRAINT "SOL_CANCELACION_ESTADO_INT_FK"
FOREIGN KEY (
  "COD_ESTADO_INT_CANCELACION"
)
REFERENCES "ESTADO_INT_CANCELACION" (
  "COD_ESTADO_INT_CANCELACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_CANCELACION" ADD CONSTRAINT "SOL_CANCELACION_PETICION_FK"
FOREIGN KEY (
  "COD_PETICION"
)
REFERENCES "PETICIONES" (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_CANCELACION" ADD CONSTRAINT "SOL_CANCELACION_TIPO_DOC_FK"
FOREIGN KEY (
  "COD_TIPO_DOCUMENTACION"
)
REFERENCES "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_EJECUCION" ADD CONSTRAINT "SOL_EJECUCION_ESTADO_INT_FK"
FOREIGN KEY (
  "COD_ESTADO_INT_EJECUCION"
)
REFERENCES "ESTADO_INT_EJECUCION" (
  "COD_ESTADO_INT_EJECUCION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_EJECUCION" ADD CONSTRAINT "SOL_EJECUCION_ESTADO_RESP_FK"
FOREIGN KEY (
  "COD_ESTADO_RESP_EJECUCION"
)
REFERENCES "ESTADO_RESP_EJECUCION" (
  "COD_ESTADO_RESP_EJECUCION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_EJECUCION" ADD CONSTRAINT "SOL_EJECUCION_PET_FK"
FOREIGN KEY (
  "COD_PETICION"
)
REFERENCES "PETICIONES" (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_EJECUCION" ADD CONSTRAINT "SOL_EJECUCION_TIPO_DOC_FK"
FOREIGN KEY (
  "COD_TIPO_DOCUMENTACION"
)
REFERENCES "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "SOLICITUDES_LEVANTAMIENTO" ADD CONSTRAINT "SOL_LEVANTAMIENTO_PETICION_FK"
FOREIGN KEY (
  "COD_PETICION"
)
REFERENCES "PETICIONES" (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_LEVANTAMIENTO" ADD CONSTRAINT "SOL_LEVANT_ESTADO_INT_FK"
FOREIGN KEY (
  "COD_ESTADO_INT_LEVANTAMIENTO"
)
REFERENCES "ESTADO_INT_LEVANTAMIENTO" (
  "COD_ESTADO_INT_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_LEVANTAMIENTO" ADD CONSTRAINT "SOL_LEVANT_ESTADO_RESP_FK"
FOREIGN KEY (
  "COD_ESTADO_RESP_LEVANTAMIENTO"
)
REFERENCES "ESTADO_RESP_LEVANTAMIENTO" (
  "COD_ESTADO_RESP_LEVANTAMIENTO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_LEVANTAMIENTO" ADD CONSTRAINT "SOL_LEVANT_TIPO_DOC_FK"
FOREIGN KEY (
  "COD_TIPO_DOCUMENTACION"
)
REFERENCES "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_TRABA" ADD CONSTRAINT "SOL_TRABA_ESTADO_INT_FK"
FOREIGN KEY (
  "COD_ESTADO_INT_TRABA"
)
REFERENCES "ESTADO_INT_TRABA" (
  "COD_ESTADO_INT_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_TRABA" ADD CONSTRAINT "SOL_TRABA_ESTADO_RESP_FK"
FOREIGN KEY (
  "COD_ESTADO_RESP_TRABA"
)
REFERENCES "ESTADO_RESP_TRABA" (
  "COD_ESTADO_RESP_TRABA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_TRABA" ADD CONSTRAINT "SOL_TRABA_PETICIONES_FK"
FOREIGN KEY (
  "COD_PETICION"
)
REFERENCES "PETICIONES" (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "SOLICITUDES_TRABA" ADD CONSTRAINT "SOL_TRABA_TIPO_DOC_FK"
FOREIGN KEY (
  "COD_TIPO_DOCUMENTACION"
)
REFERENCES "TIPO_DOCUMENTACION" (
  "COD_TIPO_DOCUMENTACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TAREAS_PENDIENTES" ADD CONSTRAINT "TAREAS_PENDIE_FK31024906156205"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TAREAS_REALIZADAS" ADD CONSTRAINT "TAREAS_REALIZ_FK31024906174211"
FOREIGN KEY (
  "COD_CONTROL_FICHERO"
)
REFERENCES "CONTROL_FICHERO" (
  "COD_CONTROL_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "FK_TRABAS_RELATION__EMBARGO"
FOREIGN KEY (
  "COD_EMBARGO"
)
REFERENCES "EMBARGO" (
  "COD_EMBARGO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "FK_TRABAS_TRABA_C_R_CUENTAS_"
FOREIGN KEY (
  "COD_CUENTA_RECAUDACION"
)
REFERENCES "CUENTAS_RECAUDACION" (
  "COD_CUENTA_RECAUDACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "FK_TRABAS_TRABA_C_I_CUENTAS_"
FOREIGN KEY (
  "COD_CUENTA_INMOVILIZACION"
)
REFERENCES "CUENTAS_INMOVILIZACION" (
  "COD_CUENTA_INMOVILIZACION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "TRABAS" ADD CONSTRAINT "FK_TRABAS_COD_ESTAD_ESTADO_T"
FOREIGN KEY (
  "COD_ESTADO"
)
REFERENCES "ESTADO_TRABA" (
  "COD_ESTADO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

--- FIN SCRIPT DEL DDL INICIAL. ---

----- NUEVOS DDLs: ------
-- Nuevas sequences:

CREATE SEQUENCE SEC_CONTROL_FICHERO INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_CUENTA_EMBARGO INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_CUENTA_TRABA INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_EMBARGO INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_ENTIDADES_ORDENANTES INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_ERROR_TRABA INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_FICHERO_FINAL INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_PETICION_INFORMACION INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE SEC_TRABAS INCREMENT BY 1 MINVALUE 100000 NOCYCLE NOCACHE NOORDER
/

CREATE SEQUENCE COD_AUDITORIA_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20
/

-- Nuevos campos en PETICION_INFORMACION:
ALTER TABLE PETICION_INFORMACION ADD (
	RAZON_SOCIAL_INTERNA VARCHAR2(100),
	IND_CASO_REVISADO VARCHAR2(1) DEFAULT 'N'
)
/

-- Nuevos campos en ENTIDADES_COMUNICADORAS:
ALTER TABLE ENTIDADES_COMUNICADORAS ADD (
	"DIAS_RESPUESTA_F1" NUMBER, 
	"DIAS_RESPUESTA_F3" NUMBER, 
	"DIAS_RESPUESTA_F6" NUMBER, 
	"BIC" VARCHAR2(100 BYTE), 
	"IBAN" VARCHAR2(100 BYTE), 
	"CUENTA" VARCHAR2(100 BYTE)
)
/

-- Nuevos campos en CONTROL_FICHERO:
ALTER TABLE CONTROL_FICHERO ADD (
	"COD_ESTADO" NUMBER, 
	"FICHERO_RESPUESTA" VARCHAR2(100 BYTE), 
	"FECHA_MAXIMA_RESPUESTA" NUMBER, 
	"FECHA_GENERACION_RESPUESTA" NUMBER
)
/

-- Nueva tabla PETICION_INFORMACION_CUENTAS:
CREATE TABLE PETICION_INFORMACION_CUENTAS (
    "COD_PETICION_INFORMACION" CHAR(10 BYTE) NOT NULL ENABLE, 
    "IBAN" VARCHAR2(47 BYTE) NOT NULL ENABLE, 
    "CUENTA" VARCHAR2(20 BYTE),
    "ESTADO_CUENTA" VARCHAR2(10 BYTE)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/ 

ALTER TABLE PETICION_INFORMACION_CUENTAS ADD CONSTRAINT "PETINFO_CUENTAS_PK"
PRIMARY KEY  ("COD_PETICION_INFORMACION", "IBAN")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE PETICION_INFORMACION_CUENTAS ADD CONSTRAINT "PETINFO_CUENTAS_PETINFO_FK"
FOREIGN KEY (
  "COD_PETICION_INFORMACION"
)
REFERENCES "PETICION_INFORMACION" (
  "COD_PETICION"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/
  
-- Nueva tabla ESTADO_CTRLFICHERO:
CREATE TABLE ESTADO_CTRLFICHERO (
    "COD_TIPO_FICHERO" NUMBER, 
	"COD_ESTADO" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/ 

ALTER TABLE "ESTADO_CTRLFICHERO" ADD CONSTRAINT "ESTADO_CTRLFICHERO_PK"
PRIMARY KEY  ("COD_TIPO_FICHERO", "COD_ESTADO")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "ESTADO_CTRLFICHERO" ADD CONSTRAINT "ESTADO_CTRLF_TIPOF_FK"
FOREIGN KEY (
  "COD_TIPO_FICHERO"
)
REFERENCES "TIPO_FICHERO" (
  "COD_TIPO_FICHERO"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

-- Nueva tabla H_CONTROL_FICHERO:
 CREATE TABLE H_CONTROL_FICHERO
   (	"COD_CONTROL_FICHERO" NUMBER NOT NULL ENABLE, 
	"COD_TIPO_FICHERO" NUMBER NOT NULL ENABLE, 
	"COD_ENTIDAD_PRESENTADORA" NUMBER NOT NULL ENABLE, 
	"FECHA_COMIENZO_CICLO" NUMBER(8,0), 
	"FECHA_CREACION" NUMBER(8,0), 
	"NOMBRE_FICHERO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"ISO_MONEDA" VARCHAR2(3 BYTE), 
	"FECHA_INCORPORACION" NUMBER(14,0), 
	"USUARIO_ULT_MODIFICACION" VARCHAR2(10 BYTE), 
	"F_ULTIMA_MODIFICACION" NUMBER(14,0), 
	"NUM_CRC" VARCHAR2(30 BYTE), 
	"IND_PROCESADO" VARCHAR2(1 BYTE), 
	"NUM_ENVIO" VARCHAR2(8 BYTE), 
	"IND_6301" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"IND_CGPJ" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"COD_ESTADO" NUMBER, 
	"FICHERO_RESPUESTA" VARCHAR2(100 BYTE), 
	"FECHA_MAXIMA_RESPUESTA" NUMBER, 
	"FECHA_GENERACION_RESPUESTA" NUMBER
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE "H_CONTROL_FICHERO" ADD CONSTRAINT "H_CONTROL_FICHERO_PK"
PRIMARY KEY  ("COD_CONTROL_FICHERO", "CHANGE_TIMESTAMP")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

-- Nueva tabla H_PETICION_INFORMACION:
 CREATE TABLE H_PETICION_INFORMACION
  (	"COD_PETICION" CHAR(10 BYTE) NOT NULL ENABLE, 
	"COD_CONTROL_FICHERO" NUMBER, 
	"NIF" VARCHAR2(9 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(40 BYTE), 
	"DOMICILIO" VARCHAR2(39 BYTE), 
	"MUNICIPIO" VARCHAR2(12 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(5 BYTE), 
	"NUMERO_EMBARGO" VARCHAR2(13 BYTE), 
	"CUENTA1" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD1" VARCHAR2(12 BYTE), 
	"CUENTA2" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD2" VARCHAR2(12 BYTE), 
	"CUENTA3" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD3" VARCHAR2(20 BYTE), 
	"IND_INFORMACION_CORRECTA" VARCHAR2(1 BYTE), 
	"F_ULTIMA_MODIFICACION" NUMBER(14,0), 
	"USUARIO_ULT_MODIFICACION" VARCHAR2(10 BYTE), 
	"COD_ENTIDAD_ORDENANTE" NUMBER NOT NULL ENABLE, 
	"TIPO_DEUDA" VARCHAR2(2 BYTE), 
	"IND_MAS_CUENTAS" VARCHAR2(1 BYTE), 
	"COD_SUCURSAL" NUMBER, 
	"COD_FICHERO_RESPUESTA" NUMBER, 
	"CUENTA4" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD4" VARCHAR2(12 BYTE), 
	"CUENTA5" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD5" VARCHAR2(12 BYTE), 
	"CUENTA6" VARCHAR2(20 BYTE), 
	"CLAVE_SEGURIDAD6" VARCHAR2(12 BYTE), 
	"IBAN1" VARCHAR2(24 BYTE), 
	"IBAN2" VARCHAR2(24 BYTE), 
	"IBAN3" VARCHAR2(24 BYTE), 
	"IBAN4" VARCHAR2(24 BYTE), 
	"IBAN5" VARCHAR2(24 BYTE), 
	"IBAN6" VARCHAR2(24 BYTE), 
	"COD_DEUDA_DEUDOR" VARCHAR2(8 BYTE), 
	"RAZON_SOCIAL_INTERNA" VARCHAR2(100 BYTE), 
	"IND_CASO_REVISADO" VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE "H_PETICION_INFORMACION" ADD CONSTRAINT "PK_H_PETICION_INFORMACION"
PRIMARY KEY  ("COD_PETICION", "CHANGE_TIMESTAMP")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE CONTROL_FICHERO ADD COD_CONTROL_FICHERO_RESPUESTA NUMBER;
ALTER TABLE CONTROL_FICHERO DROP COLUMN FICHERO_RESPUESTA;
ALTER TABLE CONTROL_FICHERO ADD COD_CONTROL_FICHERO_ORIGEN NUMBER;
ALTER TABLE CONTROL_FICHERO ADD COD_TAREA NUMBER;
ALTER TABLE CONTROL_FICHERO ADD CONSTRAINT CONTROL_FICHERO_RESPUESTA_FK FOREIGN KEY (COD_CONTROL_FICHERO_RESPUESTA) REFERENCES CONTROL_FICHERO(COD_CONTROL_FICHERO);
ALTER TABLE CONTROL_FICHERO ADD CONSTRAINT CONTROL_FICHERO_ORIGEN_FK FOREIGN KEY (COD_CONTROL_FICHERO_ORIGEN) REFERENCES CONTROL_FICHERO(COD_CONTROL_FICHERO);


ALTER TABLE H_CONTROL_FICHERO ADD COD_CONTROL_FICHERO_RESPUESTA NUMBER;
ALTER TABLE H_CONTROL_FICHERO DROP COLUMN FICHERO_RESPUESTA;
ALTER TABLE H_CONTROL_FICHERO ADD COD_CONTROL_FICHERO_ORIGEN NUMBER;
ALTER TABLE H_CONTROL_FICHERO ADD COD_TAREA NUMBER;
--ALTER TABLE H_CONTROL_FICHERO ADD CONSTRAINT H_CONTROL_FICHERO_RESPUESTA_FK FOREIGN KEY (COD_CONTROL_FICHERO_RESPUESTA) REFERENCES H_CONTROL_FICHERO(COD_CONTROL_FICHERO);
--ALTER TABLE H_CONTROL_FICHERO ADD CONSTRAINT H_CONTROL_FICHERO_ORIGEN_FK FOREIGN KEY (COD_CONTROL_FICHERO_ORIGEN) REFERENCES H_CONTROL_FICHERO(COD_CONTROL_FICHERO);

ALTER TABLE H_CONTROL_FICHERO ADD CHANGE_TIMESTAMP TIMESTAMP(9) NOT NULL;
ALTER TABLE H_PETICION_INFORMACION ADD CHANGE_TIMESTAMP TIMESTAMP(9) NOT NULL;


-- Nuevos campos en EMBARGO:
ALTER TABLE EMBARGO ADD (
	RAZON_SOCIAL_INTERNA VARCHAR2(100)
)
/


-- Nueva tabla CUENTA_TRABA_ACTUACION:
 CREATE TABLE CUENTA_TRABA_ACTUACION 
(	"COD_ACTUACION" CHAR(2 BYTE), 
	"DESCRIPCION" VARCHAR2(60 BYTE) NOT NULL ENABLE
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE CUENTA_TRABA_ACTUACION ADD CONSTRAINT "CUENTA_TRABA_ACTUACION_PK"
PRIMARY KEY  ("COD_ACTUACION")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

-- Nueva tabla del historico de embargos:
CREATE TABLE "H_EMBARGO" (
  "COD_EMBARGO" NUMBER NOT NULL
 ,"COD_AUDITORIA" NUMBER NOT NULL
 ,"COD_CONTROL_FICHERO" NUMBER NOT NULL
 ,"COD_ENTIDAD_ORDENANTE" NUMBER NOT NULL
 ,"NIF" VARCHAR2(9)
 ,"NOMBRE" VARCHAR2(100)
 ,"SIGLAS_VP" VARCHAR2(2)
 ,"NOMBRE_VP" VARCHAR2(25)
 ,"NUMERO" NUMBER
 ,"LETRA" VARCHAR2(1)
 ,"ESCALERA" VARCHAR2(2)
 ,"PISO" VARCHAR2(2)
 ,"PUERTA" VARCHAR2(2)
 ,"MUNICIPIO" VARCHAR2(12)
 ,"CODIGO_POSTAL" VARCHAR2(5)
 ,"NUMERO_EMBARGO" VARCHAR2(40)
 ,"IMPORTE" NUMBER
 ,"FECHA_GENERACION" NUMBER(8,0)
 ,"FECHA_LIMITE_TRABA" NUMBER(8,0)
 ,"ISO_MONEDA" VARCHAR2(3)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"COD_SUCURSAL" NUMBER
 ,"DOMICILIO" VARCHAR2(39)
 ,"TIPO_DEUDA" VARCHAR2(2)
 ,"IND_PROCESADO" CHAR(1)
 ,"DATREGCOMDET" VARCHAR2(200) DEFAULT NULL
 ,"COD_DEUDA_DEUDOR" VARCHAR2(8)
 ,"RAZON_SOCIAL_INTERNA" VARCHAR2(100)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE "H_EMBARGO" ADD CONSTRAINT "PK_H_EMBARGO"
PRIMARY KEY  ("COD_EMBARGO", "COD_AUDITORIA")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

-- Nueva tabla del historico de trabas:
CREATE TABLE "H_TRABAS" (
  "COD_TRABA" NUMBER NOT NULL
 ,"COD_AUDITORIA" NUMBER NOT NULL
 ,"COD_EMBARGO" NUMBER NOT NULL
 ,"COD_CUENTA_RECAUDACION" NUMBER NOT NULL
 ,"COD_CUENTA_INMOVILIZACION" NUMBER NOT NULL
 ,"IMPORTE_TRABADO" NUMBER
 ,"FECHA_TRABA" NUMBER(8,0)
 ,"IND_MAS_CUENTAS" NUMBER
 ,"FECHA_LIMITE" NUMBER(14,0)
 ,"IND_MODIFICADO" VARCHAR2(1)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"COD_ESTADO" NUMBER NOT NULL
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE "H_TRABAS" ADD CONSTRAINT "PK_H_TRABAS"
PRIMARY KEY  ("COD_TRABA", "COD_AUDITORIA")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "H_TRABAS" ADD CONSTRAINT "FK_H_TRABAS_RELATION_H_EMBARGO"
FOREIGN KEY (
  "COD_EMBARGO","COD_AUDITORIA"
)
REFERENCES "H_EMBARGO" (
  "COD_EMBARGO","COD_AUDITORIA"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE H_TRABAS
DISABLE CONSTRAINT "FK_H_TRABAS_RELATION_H_EMBARGO"
/

-- Nuevos campos en CUENTA_TRABA:
ALTER TABLE CUENTA_TRABA ADD (
	"ORIGEN_EMB" VARCHAR2(1), 
	"AGREGAR_A_TRABA" VARCHAR2(1),
	"ESTADO_CUENTA" VARCHAR2(10),
	"DIVISA" VARCHAR2(3)
)
/

-- Nueva tabla del historico de cuentas de trabas:
CREATE TABLE "H_CUENTA_TRABA" (
  "COD_CUENTA_TRABA" NUMBER NOT NULL
 ,"COD_AUDITORIA" NUMBER NOT NULL
 ,"COD_TRABA" NUMBER NOT NULL
 ,"CUENTA" VARCHAR2(20)
 ,"IMPORTE" NUMBER
 ,"ACTUACION" VARCHAR2(2)
 ,"F_ULTIMA_MODIFICACION" NUMBER(14,0)
 ,"USUARIO_ULT_MODIFICACION" VARCHAR2(10)
 ,"NUMERO_ORDEN_CUENTA" NUMBER
 ,"COD_ESTADO" NUMBER NOT NULL
 ,"CAMBIO" NUMBER
 ,"IBAN" VARCHAR2(24)
 ,"ORIGEN_EMB" VARCHAR2(1) 
 ,"AGREGAR_A_TRABA" VARCHAR2(1)
 ,"ESTADO_CUENTA" VARCHAR2(10)
 ,"DIVISA" VARCHAR2(3)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 40960
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE "H_CUENTA_TRABA" ADD CONSTRAINT "PK_H_CUENTA_TRABA"
PRIMARY KEY  ("COD_CUENTA_TRABA", "COD_AUDITORIA")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

-- Nuevos campos en ESTADO_TRABA:
ALTER TABLE ESTADO_TRABA ADD (
	"OCULTAR_A_USUARIO" VARCHAR2(1)
)
/

-- Nuevos campos en CUENTA_TRABA_ACTUACION
alter table CUENTA_TRABA_ACTUACION
add 
(	"TIPO_ENTIDAD" VARCHAR2(10 BYTE), 
	"COD_EXTERNO_ACTUACION" CHAR(2 BYTE)
)
/

-- Modificaciones para la nueva tabla RAZON_SOCIAL_INTERNA:
ALTER TABLE PETICION_INFORMACION DROP COLUMN RAZON_SOCIAL_INTERNA
/
ALTER TABLE EMBARGO DROP COLUMN RAZON_SOCIAL_INTERNA
/
ALTER TABLE LEVANTAMIENTO_TRABA ADD NIF VARCHAR2(9 CHAR)
/

CREATE TABLE DATOS_CLIENTE 
(	"NIF" VARCHAR2(9 CHAR) NOT NULL, 
	"NOMBRE" VARCHAR2(100 CHAR),
	"DOMICILIO" VARCHAR2(100 CHAR),
	"MUNICIPIO" VARCHAR2(50 CHAR),
	"CODIGO_POSTAL" VARCHAR2(5 CHAR),
	"IND_PENDIENTE_DWH" VARCHAR2(1) DEFAULT 'N',
	"F_ULTIMA_MODIFICACION" NUMBER(14,0),
	"USUARIO_ULT_MODIFICACION" VARCHAR2(10 CHAR)
)
TABLESPACE "EMBARGOS2_DATA"
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
         INITIAL 26255360
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
        )
/

ALTER TABLE DATOS_CLIENTE ADD CONSTRAINT "DATOS_CLIENTE_PK"
PRIMARY KEY  ("NIF")
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "PETICION_INFORMACION" ADD CONSTRAINT "FK_PETINF_RELATION_DATOSCLIENT"
FOREIGN KEY (
  "NIF"
)
REFERENCES "DATOS_CLIENTE" (
  "NIF"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/


ALTER TABLE "EMBARGO" ADD CONSTRAINT "FK_EMBARG_RELATION_DATOSCLIENT"
FOREIGN KEY (
  "NIF"
)
REFERENCES "DATOS_CLIENTE" (
  "NIF"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/

ALTER TABLE "LEVANTAMIENTO_TRABA" ADD CONSTRAINT "FK_LEVTRA_RELATION_DATOSCLIENT"
FOREIGN KEY (
  "NIF"
)
REFERENCES "DATOS_CLIENTE" (
  "NIF"
)
NOT DEFERRABLE
INITIALLY IMMEDIATE
ENABLE NOVALIDATE
/
