
DELETE FROM "ERROR_TRABA";
DELETE FROM "CONTROL_FICHERO_TRABA";
DELETE FROM "HISTORIAL_ESTADO_TRABA";

DELETE FROM "CUENTA_RESULTADO_EMBARGO";
DELETE FROM "CUENTA_LEVANTAMIENTO";
DELETE FROM "CUENTA_TRABA";
DELETE FROM "CUENTA_EMBARGO";

DELETE FROM "RESULTADO_EMBARGO";
DELETE FROM "LEVANTAMIENTO_TRABA";
DELETE FROM "TRABAS";
DELETE FROM "EMBARGO";

DELETE FROM "FICHERO_FINAL";

DELETE FROM "PETICION_INFORMACION_CUENTAS";
DELETE FROM "PETICION_INFORMACION";

DELETE FROM "SOLICITUDES_CANCELACION";
DELETE FROM "SOLICITUDES_EJECUCION";
DELETE FROM "SOLICITUDES_LEVANTAMIENTO";
DELETE FROM "SOLICITUDES_TRABA";
DELETE FROM "PETICIONES";

DELETE FROM "TAREAS_PENDIENTES";
DELETE FROM "TAREAS_REALIZADAS";

DELETE FROM "DETALLE_CONTROL_FICHERO";
DELETE FROM "CONTROL_FICHERO";


