DROP SEQUENCE AUDITORIA_SEQ;
DROP SEQUENCE SEC_APODERADOS;
DROP SEQUENCE SEC_CONTROL_FICHERO;
DROP SEQUENCE SEC_CUENTA_EMBARGO;
DROP SEQUENCE SEC_CUENTA_LEVANTAMIENTO;
DROP SEQUENCE SEC_CUENTA_RESULTADO_EMBARGO;
DROP SEQUENCE SEC_CUENTA_TRABA;
DROP SEQUENCE SEC_EMBARGO;
DROP SEQUENCE SEC_ENTIDADES_ORDENANTES;
DROP SEQUENCE SEC_ERROR_TRABA;
DROP SEQUENCE SEC_FICHERO_FINAL;
DROP SEQUENCE SEC_LEVANTAMIENTO_TRABA;
DROP SEQUENCE SEC_PETICION_INFORMACION;
DROP SEQUENCE SEC_RESULTADO_EMBARGO;
DROP SEQUENCE SEC_TAREAS_PENDIENTES;
DROP SEQUENCE SEC_TRABAS;

DROP VIEW "SOLICITUDES_CGPJ";


DROP TABLE "ERROR_TRABA";
DROP TABLE "CONTROL_FICHERO_TRABA";
DROP TABLE "HISTORIAL_ESTADO_TRABA";

DROP TABLE "CUENTA_RESULTADO_EMBARGO";
DROP TABLE "CUENTA_LEVANTAMIENTO";
DROP TABLE "CUENTA_TRABA";
DROP TABLE "CUENTA_EMBARGO";

DROP TABLE "RESULTADO_EMBARGO";
DROP TABLE "LEVANTAMIENTO_TRABA";
DROP TABLE "TRABAS";
DROP TABLE "EMBARGO";

DROP TABLE "FICHERO_FINAL";

DROP TABLE "PETICION_INFORMACION_CUENTAS";
DROP TABLE "PETICION_INFORMACION";

DROP TABLE "SOLICITUDES_CANCELACION";
DROP TABLE "SOLICITUDES_EJECUCION";
DROP TABLE "SOLICITUDES_LEVANTAMIENTO";
DROP TABLE "SOLICITUDES_TRABA";
DROP TABLE "PETICIONES";

DROP TABLE "TAREAS_PENDIENTES";
DROP TABLE "TAREAS_REALIZADAS";

DROP TABLE "DETALLE_CONTROL_FICHERO";
DROP TABLE "CONTROL_FICHERO";

DROP TABLE APODERADOS;
DROP TABLE AUDITORIA;
DROP TABLE CUENTAS_INMOVILIZACION;
DROP TABLE CUENTA_TRABA_ACTUACION;
DROP TABLE CUENTA_TRABA_CGPJ_COPY;
DROP TABLE ENTIDADES_ORDENANTES;
DROP TABLE ENTIDADES_COMUNICADORAS;
DROP TABLE CUENTAS_RECAUDACION;
DROP TABLE ERRORES;
DROP TABLE ESTADO_CONTABILIZACION;
DROP TABLE ESTADO_CTRLFICHERO;
DROP TABLE ESTADO_INT_CANCELACION;
DROP TABLE ESTADO_INT_EJECUCION;
DROP TABLE ESTADO_INT_LEVANTAMIENTO;
DROP TABLE ESTADO_INT_PETICION;
DROP TABLE ESTADO_INT_TRABA;
DROP TABLE ESTADO_LEVANTAMIENTO;
DROP TABLE ESTADO_PETICION_INFORMACION;
DROP TABLE ESTADO_PRIMARIO_PETICION;
DROP TABLE ESTADO_PRIMARIO_RESP;
DROP TABLE ESTADO_RESP_EJECUCION;
DROP TABLE ESTADO_RESP_LEVANTAMIENTO;
DROP TABLE ESTADO_RESP_TRABA;
DROP TABLE ESTADO_RESULTADO_EMBARGO;
DROP TABLE ESTADO_SECUNDARIO_RESP;
DROP TABLE ESTADO_TRABA;
DROP TABLE FESTIVO;
DROP TABLE SEMAFORO;
DROP TABLE SEMAFORO_CGPJ;
DROP TABLE TIPO_DOCUMENTACION;
DROP TABLE TIPO_FICHERO;

-- PROCEDURE DELETION IS NOT REQUIRED
DROP FUNCTION CIERRA_SEMAFORO;
DROP FUNCTION DD_MM_AAAA;
DROP FUNCTION DD_MM_AAAA_HH_MM_SS;
DROP FUNCTION FORMATO_CCC;
