spring:
  data:
    rest:
      default-page-size: 50
  datasource:
    initialize: false
    continue-on-error: false
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: COMM_EMBARGOS_DES
    password: PASSWORD
    sql-script-encoding: UTF-8
  mvc:
    favicon:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always 
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
  jta:
    enable: false
  profiles:
    active: 
    - LOCAL
    - YAMLDB
  ds-comun:
    url: jdbc:oracle:thin:@172.21.0.123:1521:DBADQUIRA
    username: COMM_COMUNES_DES
    password: comm_c0mu
    driver-class-name: oracle.jdbc.driver.OracleDriver
# ds-comun:
#   url: jdbc:oracle:thin:@localhost:xe
#   username: COMM_COMUNES_DES
#   password: PASSWORD
#   driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  servlet-path: /*
  context-path: /embargos
  port: 8090


commerzbank:
  embargos:
    files:
      configuration-poll-time-in-seconds: 60
      monitoring-interval-in-millis: 10000
      suffix-file-filter-pet: pet
      suffix-file-filter-inf: inf
      suffix-file-filter-emb: emb
      suffix-file-filter-tra: tra
      suffix-file-filter-lev: lev
      suffix-file-filter-err: err
      suffix-file-filter-fin: fin
      suffix-file-filter-con: con
      path:
        norma63:
          incoming: c:/temp
          processing: c:/temp
          processed: c:/temp
          generated: c:/temp
          error: c:/temp
          encoding: UTF-8
        aeat:
          incoming: c:/temp
          processing: c:/temp
          processed: c:/temp
          generated: c:/temp
          error: c:/temp
          encoding: UTF-8
    beanio:
      config-path:
        cuaderno63: beanio/cuaderno63.xml
        aeat: beanio/aeat.xml
  comunes:
    beanio:
      config-path:
        contabilidad: beanio/contabilidad_salida.xml
        mt942: beanio/mt942.xml
  cuentaRetencion: 170123456789EUR
  cuentaRecaudacion:
    cuenta: 170123456789EUR
    oficina: 171
    iban: ES0012341234123412341234
  fase1:
    notificacion:
      to: a@b.c
      cc: a@b.c
  email:
    to: a@b.c
    from: a@b.c

  contabilizacion:
    mt942: c:/temp
    fase5:
      callback:

    fase3:
      callback:
    saliente: c:/temp
    generados: c:/temp

  levantamiento:
    importeMaximoAutomaticoDivisa:

tsp:
  dominio:
  jasper:
    temp: c:/temp

datawarehouse:
  endpoint:
    client-account:

comunes:
  smtp:
    host:
    port:
    username:
    password:


