CREATE OR REPLACE FUNCTION "DD_MM_AAAA_HH_MM_SS"    (Fecha Number) RETURN VARCHAR2 is
--esta funcion devuelve con formato dd/mm/aaaa hh:mm:ss
--una fecha pasada con formato aaaammddhhmmss

    DIA VARCHAR2(2);
    MES VARCHAR2(2);
   ANIO VARCHAR2(4);
   HORA VARCHAR2(2);
   MINUTO VARCHAR2(2);
   SEGUNDO VARCHAR2(2);
   RESULTADO VARCHAR2(19);
BEGIN
    RESULTADO:=TO_CHAR(Fecha);

    DIA:=SUBSTR(RESULTADO,7,2);
    MES:=SUBSTR(RESULTADO,5,2);
    ANIO:=SUBSTR(RESULTADO,1,4);
 	  HORA:=SUBSTR(RESULTADO,9,2);
 	  MINUTO:=SUBSTR(RESULTADO,11,2);
 	  SEGUNDO:=SUBSTR(RESULTADO,13,2);
   RESULTADO:=CONCAT(DIA,'/');
   RESULTADO:=CONCAT(RESULTADO,MES);
   RESULTADO:=CONCAT(RESULTADO,'/');
   RESULTADO:=CONCAT(RESULTADO,ANIO);
   RESULTADO:=CONCAT(RESULTADO,' ');
   RESULTADO:=CONCAT(RESULTADO,HORA);
   RESULTADO:=CONCAT(RESULTADO,':');
   RESULTADO:=CONCAT(RESULTADO,MINUTO);
   RESULTADO:=CONCAT(RESULTADO,':');
   RESULTADO:=CONCAT(RESULTADO,SEGUNDO);
 return(RESULTADO);


end;
